# Form implementation generated from reading ui file '.\create_user.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets
from access_connector import (create_new_user,
                              user_database, 
                              delete_user_from_database, 
                              change_password)
from salt_pepper.password_hesher import hash_password_sha256
from PyQt6.QtGui import QFont, QPalette, QColor

''' global variables'''

''' classes '''
class Ui_Form(object):
    def setupUi(self,
                Form,
                language,
                app_settings):
        
        Form.setObjectName("Form")
        Form.resize(619, 406)
        self.Form = Form
        self.selected_language = language
        self.app_settings = app_settings
        
        
        """Application settings"""
        font = QFont(self.app_settings["font_name"],
                     self.app_settings["font_size"])
        self.Form.setFont(font)

        palette = QPalette()
        # font color
        palette.setColor(QPalette.ColorRole.WindowText,
                         QColor(*self.app_settings["font_color"]))
        # background color
        palette.setColor(QPalette.ColorRole.Window, 
                         QColor(*self.app_settings["background_color"]))
        self.Form.setPalette(palette) 
        
        # group box create user
        self.group_box_create_user = QtWidgets.QGroupBox(parent=Form)
        self.group_box_create_user.setGeometry(QtCore.QRect(20, 20, 281, 181))
        self.group_box_create_user.setObjectName("group_box_create_user")
        
        # button create user
        self.button_create = QtWidgets.QPushButton(parent=self.group_box_create_user)
        self.button_create.setGeometry(QtCore.QRect(20, 130, 241, 24))
        self.button_create.setObjectName("button_create")
        self.button_create.clicked.connect(self.create_new_user)
        
        self.line_edit_username = QtWidgets.QLineEdit(parent=self.group_box_create_user)
        self.line_edit_username.setGeometry(QtCore.QRect(100, 40, 161, 22))
        self.line_edit_username.setObjectName("line_edit_username")
        self.line_edit_password = QtWidgets.QLineEdit(parent=self.group_box_create_user)
        self.line_edit_password.setGeometry(QtCore.QRect(100, 80, 161, 22))
        self.line_edit_password.setObjectName("line_edit_password")
        self.label_username = QtWidgets.QLabel(parent=self.group_box_create_user)
        self.label_username.setGeometry(QtCore.QRect(20, 40, 81, 21))
        self.label_username.setObjectName("label_username")
        self.label_password = QtWidgets.QLabel(parent=self.group_box_create_user)
        self.label_password.setGeometry(QtCore.QRect(20, 80, 81, 21))
        self.label_password.setObjectName("label_password")
        
        # group box change password
        self.group_box_change_password = QtWidgets.QGroupBox(parent=Form)
        self.group_box_change_password.setGeometry(QtCore.QRect(320, 20, 281, 181))
        self.group_box_change_password.setObjectName("group_box_change_password")
        self.label_change_username = QtWidgets.QLabel(parent=self.group_box_change_password)
        self.label_change_username.setGeometry(QtCore.QRect(20, 40, 81, 21))
        self.label_change_username.setObjectName("label_change_username")
        self.label_change_password = QtWidgets.QLabel(parent=self.group_box_change_password)
        self.label_change_password.setGeometry(QtCore.QRect(20, 80, 81, 21))
        self.label_change_password.setObjectName("label_change_password")
        self.edit_username_change = QtWidgets.QLineEdit(parent=self.group_box_change_password)
        self.edit_username_change.setGeometry(QtCore.QRect(100, 40, 161, 20))
        self.edit_username_change.setObjectName("edit_username_change")
        self.edit_password_change = QtWidgets.QLineEdit(parent=self.group_box_change_password)
        self.edit_password_change.setGeometry(QtCore.QRect(100, 80, 161, 20))
        self.edit_password_change.setObjectName("edit_password_change")
        self.button_change_password = QtWidgets.QPushButton(parent=self.group_box_change_password)
        self.button_change_password.setGeometry(QtCore.QRect(20, 130, 241, 23))
        self.button_change_password.setObjectName("button_change_password")
        self.button_change_password.clicked.connect(self.password_change)
        
        # group box - delete users
        self.group_box_delete_users = QtWidgets.QGroupBox(parent=Form)
        self.group_box_delete_users.setGeometry(QtCore.QRect(20, 210, 281, 181))
        self.group_box_delete_users.setObjectName("group_box_delete_users")
        self.label_delete_user = QtWidgets.QLabel(parent=self.group_box_delete_users)
        self.label_delete_user.setGeometry(QtCore.QRect(20, 40, 81, 21))
        self.label_delete_user.setObjectName("label_delete_user")
        self.edit_delete_user = QtWidgets.QLineEdit(parent=self.group_box_delete_users)
        self.edit_delete_user.setGeometry(QtCore.QRect(110, 40, 151, 21))
        self.edit_delete_user.setObjectName("edit_delete_user")
        self.button_delete_user = QtWidgets.QPushButton(parent=self.group_box_delete_users)
        self.button_delete_user.setGeometry(QtCore.QRect(20, 70, 241, 23))
        self.button_delete_user.setObjectName("button_delete_user")
        self.button_delete_user.clicked.connect(self.delete_user)
        
        #group box created users
        self.group_box_created_users = QtWidgets.QGroupBox(parent=Form)
        self.group_box_created_users.setGeometry(QtCore.QRect(320, 210, 281, 181))
        self.group_box_created_users.setObjectName("group_box_created_users")
        
        # table that shows usernames from database
        self.table_created_users = QtWidgets.QTableWidget(parent=self.group_box_created_users)
        self.table_created_users.setGeometry(QtCore.QRect(20, 50, 241, 131))
        self.table_created_users.setObjectName("table_created_users")
        self.array_of_users = []
        
        # button when pressed calls function show_users and shows users on table_created_users
        # QTableWidget
        self.button_show_users = QtWidgets.QPushButton(parent=self.group_box_created_users)
        self.button_show_users.setGeometry(QtCore.QRect(20, 20, 241, 23))
        self.button_show_users.setObjectName("button_show_users")
        self.button_show_users.clicked.connect(self.show_users)
        
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def password_change(self):
        confirmation_message = QtWidgets.QMessageBox(QtWidgets.QMessageBox.Icon.Question,
                                                     self.warning_title,
                                                     self.password_change_message, 
                                                     QtWidgets.QMessageBox.StandardButton.Yes | QtWidgets.QMessageBox.StandardButton.No, self.Form)
        confirmation_result = confirmation_message.exec()
        
        self.new_password = self.edit_password_change.text()
        self.new_password_heshed = hash_password_sha256(self.new_password)
        
        if confirmation_result == QtWidgets.QMessageBox.StandardButton.Yes:
            if change_password(self.edit_username_change.text(), self.new_password_heshed):
                QtWidgets.QMessageBox.warning(self.Form,
                                              self.success_title, 
                                              self.password_changed)
            else:
                QtWidgets.QMessageBox.warning(self.Form,
                                              self.error_title,
                                              self.wrong_username)
            
    def create_new_user(self):
        
        self.new_password = self.line_edit_password.text()
        self.new_password_heshed = hash_password_sha256(self.new_password)
        
        if create_new_user(self.line_edit_username.text(), self.new_password_heshed):
            QtWidgets.QMessageBox.warning(self.Form,
                                          self.success_title,
                                          self.user_created)
        else:
            QtWidgets.QMessageBox.warning(self.Form,
                                          self.error_title,
                                          self.user_exists)

    def show_users(self):
        self.array_of_users = user_database() 
        
        number_of_rows = len(self.array_of_users)
        number_of_columns = 1
        
        self.table_created_users.setRowCount(number_of_rows)
        self.table_created_users.setColumnCount(number_of_columns)
        self.table_created_users.setHorizontalHeaderLabels(["Users"])
        self.table_created_users.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.ResizeMode.Stretch)
        
        for x, column_value in enumerate(self.array_of_users):
            print(x, ' ', column_value )
            value = QtWidgets.QTableWidgetItem(str(column_value))
            self.table_created_users.setItem(x, 0, value)

    def delete_user(self):
        confirmation_message = QtWidgets.QMessageBox(QtWidgets.QMessageBox.Icon.Question,
                                                     self.warning_title,
                                                     self.delete_user_question + self.edit_delete_user.text() + " ?",
                                                     QtWidgets.QMessageBox.StandardButton.Yes | QtWidgets.QMessageBox.StandardButton.No, self.Form)
        confirmation_result = confirmation_message.exec()
        
        if confirmation_result == QtWidgets.QMessageBox.StandardButton.Yes:
            if delete_user_from_database(self.edit_delete_user.text()):
                QtWidgets.QMessageBox.warning(self.Form,
                                              self.success_title,
                                              self.user_deleted)
            else:
                QtWidgets.QMessageBox.warning(self.Form,
                                              self.error_title,
                                              self.no_user_in_database)
            
    def retranslateUi(self, Form):
        
        if self.selected_language == "English":
            _translate = QtCore.QCoreApplication.translate
            Form.setWindowTitle(_translate("Form", "Form"))
            self.group_box_create_user.setTitle(_translate("Form", "Create new user"))
            self.button_create.setText(_translate("Form", "Create new user"))
            self.label_username.setText(_translate("Form", "Username"))
            self.label_password.setText(_translate("Form", "Password"))
            self.group_box_change_password.setTitle(_translate("Form", "Change password"))
            self.label_change_username.setText(_translate("Form", "Username"))
            self.label_change_password.setText(_translate("Form", "New Password"))
            self.button_change_password.setText(_translate("Form", "Change password"))
            self.group_box_delete_users.setTitle(_translate("Form", "Delete users"))
            self.label_delete_user.setText(_translate("Form", "Username"))
            self.button_delete_user.setText(_translate("Form", "Delete user"))
            self.group_box_created_users.setTitle(_translate("Form", "Created users"))
            self.button_show_users.setText("Show users")
            warning_title = "Warning!"
            self.error_title = "Error"
            self.success_title = "Success"
            self.wrong_username = "Wrong username"
            self.password_change_message = "Are you sure you want to change the password?"
            self.password_changed = "Password changed!"
            self.user_created = "User created."
            self.user_exists = "User already exists!"
            self.delete_user_question = "Are you sure you want to delete the user: "
            self.user_deleted = "User deleted!"
            self.no_user_in_database = "User is not in database"
            
        if self.selected_language == "French":
            _translate = QtCore.QCoreApplication.translate
            Form.setWindowTitle(_translate("Form", "Formulaire"))
            self.group_box_create_user.setTitle(_translate("Form", "Créer un nouvel utilisateur"))
            self.button_create.setText(_translate("Form", "Créer un nouvel utilisateur"))
            self.label_username.setText(_translate("Form", "Nom d'utilisateur"))
            self.label_password.setText(_translate("Form", "Mot de passe"))
            self.group_box_change_password.setTitle(_translate("Form", "Modifier le mot de passe"))
            self.label_change_username.setText(_translate("Form", "Nom d'utilisateur"))
            self.label_change_password.setText(_translate("Form", "Nouveau mot de passe"))
            self.button_change_password.setText(_translate("Form", "Modifier le mot de passe"))
            self.group_box_delete_users.setTitle(_translate("Form", "Supprimer des utilisateurs"))
            self.label_delete_user.setText(_translate("Form", "Nom d'utilisateur"))
            self.button_delete_user.setText(_translate("Form", "Supprimer l'utilisateur"))
            self.group_box_created_users.setTitle(_translate("Form", "Utilisateurs créés"))
            self.button_show_users.setText("Afficher les utilisateurs")
            self.warning_title = "Attention !"
            self.error_title = "Erreur"
            self.success_title = "Succès"
            self.wrong_username = "Nom d'utilisateur incorrect"
            self.password_change_message = "Êtes-vous sûr de vouloir changer le mot de passe ?"
            self.password_changed = "Mot de passe changé !"
            self.user_created = "Utilisateur créé."
            self.user_exists = "L'utilisateur existe déjà !"
            self.delete_user_question = "Êtes-vous sûr de vouloir supprimer l'utilisateur : "
            self.user_deleted = "Utilisateur supprimé !"
            self.no_user_in_database = "L'utilisateur n'est pas dans la base de données"

            
        if self.selected_language == "Croatian":
            _translate = QtCore.QCoreApplication.translate
            Form.setWindowTitle(_translate("Form", "Obrazac"))
            self.group_box_create_user.setTitle(_translate("Form", "Stvorite novog korisnika"))
            self.button_create.setText(_translate("Form", "Stvorite novog korisnika"))
            self.label_username.setText(_translate("Form", "Korisničko ime"))
            self.label_password.setText(_translate("Form", "Lozinka"))
            self.group_box_change_password.setTitle(_translate("Form", "Promijenite lozinku"))
            self.label_change_username.setText(_translate("Form", "Korisničko ime"))
            self.label_change_password.setText(_translate("Form", "Nova lozinka"))
            self.button_change_password.setText(_translate("Form", "Promijenite lozinku"))
            self.group_box_delete_users.setTitle(_translate("Form", "Izbrišite korisnike"))
            self.label_delete_user.setText(_translate("Form", "Korisničko ime"))
            self.button_delete_user.setText(_translate("Form", "Izbrišite korisnika"))
            self.group_box_created_users.setTitle(_translate("Form", "Stvoreni korisnici"))
            self.button_show_users.setText(_translate("Form", "Prikaži korisnike"))
            self.warning_title = "Upozorenje!"
            self.error_title = "Greška"
            self.success_title = "Uspjeh"
            self.wrong_username = "Pogrešno korisničko ime"
            self.password_change_message = "Jeste li sigurni da želite promijeniti lozinku?"
            self.password_changed = "Lozinka promijenjena!"
            self.user_created = "Korisnik stvoren."
            self.user_exists = "Korisnik već postoji!"
            self.delete_user_question = "Jeste li sigurni da želite izbrisati korisnika: "
            self.user_deleted = "Korisnik izbrisan!"
            self.no_user_in_database = "Korisnik nije u bazi podataka"

        if self.selected_language == "German":
            _translate = QtCore.QCoreApplication.translate
            Form.setWindowTitle(_translate("Form", "Formular"))
            self.group_box_create_user.setTitle(_translate("Form", "Neuen Benutzer erstellen"))
            self.button_create.setText(_translate("Form", "Neuen Benutzer erstellen"))
            self.label_username.setText(_translate("Form", "Benutzername"))
            self.label_password.setText(_translate("Form", "Passwort"))
            self.group_box_change_password.setTitle(_translate("Form", "Passwort ändern"))
            self.label_change_username.setText(_translate("Form", "Benutzername"))
            self.label_change_password.setText(_translate("Form", "Neues Passwort"))
            self.button_change_password.setText(_translate("Form", "Passwort ändern"))
            self.group_box_delete_users.setTitle(_translate("Form", "Benutzer löschen"))
            self.label_delete_user.setText(_translate("Form", "Benutzername"))
            self.button_delete_user.setText(_translate("Form", "Benutzer löschen"))
            self.group_box_created_users.setTitle(_translate("Form", "Erstellte Benutzer"))
            self.button_show_users.setText(_translate("Form", "Benutzer anzeigen"))
            self.warning_title = "Warnung!"
            self.error_title = "Fehler"
            self.success_title = "Erfolg"
            self.wrong_username = "Falscher Benutzername"
            self.password_change_message = "Möchten Sie das Passwort wirklich ändern?"
            self.password_changed = "Passwort geändert!"
            self.user_created = "Benutzer erstellt."
            self.user_exists = "Benutzer existiert bereits!"
            self.delete_user_question = "Sind Sie sicher, dass Sie den Benutzer löschen möchten: "
            self.user_deleted = "Benutzer gelöscht!"
            self.no_user_in_database = "Benutzer ist nicht in der Datenbank"


        if self.selected_language == "Spanish":
            _translate = QtCore.QCoreApplication.translate
            Form.setWindowTitle(_translate("Form", "Formulario"))
            self.group_box_create_user.setTitle(_translate("Form", "Crear nuevo usuario"))
            self.button_create.setText(_translate("Form", "Crear nuevo usuario"))
            self.label_username.setText(_translate("Form", "Nombre de usuario"))
            self.label_password.setText(_translate("Form", "Contraseña"))
            self.group_box_change_password.setTitle(_translate("Form", "Cambiar contraseña"))
            self.label_change_username.setText(_translate("Form", "Nombre de usuario"))
            self.label_change_password.setText(_translate("Form", "Nueva contraseña"))
            self.button_change_password.setText(_translate("Form", "Cambiar contraseña"))
            self.group_box_delete_users.setTitle(_translate("Form", "Eliminar usuarios"))
            self.label_delete_user.setText(_translate("Form", "Nombre de usuario"))
            self.button_delete_user.setText(_translate("Form", "Eliminar usuario"))
            self.group_box_created_users.setTitle(_translate("Form", "Usuarios creados"))
            self.button_show_users.setText(_translate("Form", "Mostrar usuarios"))
            self.warning_title = "¡Advertencia!"
            self.error_title = "Error"
            self.success_title = "Éxito"
            self.wrong_username = "Nombre de usuario incorrecto"
            self.password_change_message = "¿Estás seguro de que quieres cambiar la contraseña?"
            self.password_changed = "Contraseña cambiada!"
            self.user_created = "Usuario creado."
            self.user_exists = "¡El usuario ya existe!"
            self.delete_user_question = "¿Estás seguro de que quieres eliminar al usuario: "
            self.user_deleted = "Usuario eliminado!"
            self.no_user_in_database = "Usuario no está en la base de datos"

