# Form implementation generated from reading ui file '.\database_view_window.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

# imports for GUI from pyqt6
from PyQt6 import QtCore, QtWidgets
from PyQt6.QtCore import Qt, QThread, pyqtSignal
from PyQt6.QtWidgets import QMainWindow
# database manipulation imports
from access_connector import (import_product,
                              get_table, 
                              get_table_by_filter, 
                              import_warehouse,
                              update_warehouse,
                              update_product,
                              delete_product_by_id,
                              delete_warehouse_by_id,
                              show_table,
                              import_image,
                              get_image,
                              get_product_data,
                              get_master_detail_data,
                              get_image_for_pdf,
                              get_product_sum)
# imports custom UI widgets
from show_image_form import Ui_Form
from report_form import Report_Form
# imports for RTF and PDF
import os
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from PIL import Image # for image handling in function "def get_image_data(self)"
# imports for multithreading
import time
import concurrent.futures
import threading

class Ui_MainWindow(QMainWindow):
    
    # Class fo report generation
    class Report_Generator():
        
        def __init__(self):
            self.product_data = None
            self.master_detail_data = None
        
        def return_data(self):
            return self.product_data, self.master_detail_data
        
        # function to fetch data and product report in RTF
        def get_product_data(self, type_of_request):
            data_dict = get_product_data()

            if type_of_request == "show":
                self.product_data = data_dict
                return
            if type_of_request == "generate":
                self.product_data = data_dict

                date_of_report = datetime.now().strftime("%Y-%m-%d")

                rtf_report = "{\\rtf1\\ansi\n"
                rtf_report += "Izvjestaj iz baze podataka: 'skladiste.accdb', tablica: 'proizvodi' \line "
                rtf_report += f"Datum izvjestaja: {date_of_report} \line "
                rtf_report += "--------------------------------------------------------- \line\line"

                total_amount_all_products = 0
                total_items = 0
                total_products = 0

                for product, value in self.product_data.items():
                    total_items += 1

                    product_category = value["kategorija"]
                    product_price = value["cijena"]
                    product_quantity = value["kolicina"]
                    product_warehouse_id = value["skladiste_id"]

                    total_amount_all_products += product_price * product_quantity
                    total_products += product_quantity

                    rtf_report += f"Naziv - {product} \line "
                    rtf_report += f"Kategorija - {product_category} \line "
                    rtf_report += f"Cijena - {product_price} kn \line "
                    rtf_report += f"Kolicina: {product_quantity} \line "
                    rtf_report += f"ID skladista: {product_warehouse_id} \line\line "

                rtf_report += "--------------------------------------------------------- \line "
                rtf_report += f" \line Ukupni iznos svih proizvoda iznosi: {total_amount_all_products} kn. \line "
                rtf_report += f"Ukupno stavki: {total_items} \line "
                rtf_report += f"Ukupno proizvoda: {total_products} kom. \line "
                rtf_report += "}"

                # Get the current date and time
                current_datetime = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")

                # Get the current directory of the main script
                current_directory = os.path.dirname(os.path.abspath(__file__))

                # Create the 'reports' directory if it doesn't exist
                reports_directory = os.path.join(current_directory, 'reports/products_rtf')
                if not os.path.exists(reports_directory):
                    os.makedirs(reports_directory)

                # Construct the filename with date and time
                filename = os.path.join(reports_directory, f"{current_datetime}_products.rtf")

                # Write the RTF content to the file
                with open(filename, 'w', encoding='utf-8') as rtf_file:
                    rtf_file.write(rtf_report)
                
                self.product_data = rtf_report
                print("Product report completed.")

        # function to fetch data and generate master detail report in RTF
        def get_master_detail_data(self, type_of_request):
            data_dict = get_master_detail_data()

            if type_of_request == "show":
                self.master_detail_data = data_dict
                return

            if type_of_request == "generate":
                self.product_data = data_dict

                # Get the current date and time
                current_datetime = datetime.now().strftime("%Y-%m-%d")

                # Get the current directory of the main script
                current_directory = os.path.dirname(os.path.abspath(__file__))

                # Create the 'reports' directory if it doesn't exist
                reports_directory = os.path.join(current_directory, 'reports/master_detail_pdf')
                if not os.path.exists(reports_directory):
                    os.makedirs(reports_directory)

                # Construct the filename with date and time
                filename = os.path.join(reports_directory, f"{current_datetime}_master-detail.pdf")

                # Create a PDF canvas with A4 size
                c = canvas.Canvas(filename, pagesize=A4)

                # Set initial y-coordinate for content
                y = A4[1] - 50

                sum_of_all_products = 0
                total_items = 0
                total_products = 0

                c.drawString(50, y, "Izvjestaj za master-detail (skladiste->proizvodi)")
                y -= 15
                c.drawString(50, y, f"Datum izvjestaja: {current_datetime}")
                y -= 30

                for key, products in data_dict.items():
                    c.drawString(50, y, "-" * 50)
                    y -= 15

                    c.drawString(50, y, f"Skladiste ID: {key}")
                    y -= 15

                    for product in products:
                        c.drawString(50, y, f"Naziv - {product['naziv']}")
                        y -= 15
                        c.drawString(50, y, f"Kategorija - {product['kategorija']}")
                        y -= 15
                        c.drawString(50, y, f"Cijena - {product['cijena']}")
                        y -= 15
                        c.drawString(50, y, f"Kolicina: {product['kolicina']}")
                        y -= 15
                        c.drawString(50, y, f"ID skladišta: {product['skladiste_id']}")
                        y -= 15
                        if product['privitak'] == -1:
                            c.drawString(50, y, f"Sadrzi privitak: DA")
                        else:
                            c.drawString(50, y, f"Sadrzi privitak: NE")
                        y -= 30

                        sum_of_all_products += product['cijena'] * product['kolicina']
                        total_items += 1
                        total_products += product['kolicina']

                    c.drawString(50, y, f"Statistika za skladiste ID: {key}")
                    y -= 15
                    c.drawString(50, y, f"Ukupni iznos svih proizvoda iznosi: {sum_of_all_products} kn.")
                    y -= 15
                    c.drawString(50, y, f"Ukupno stavki: {total_items}")
                    y -= 15
                    c.drawString(50, y, f"Ukupno proizvoda: {total_products} kom")
                    y -= 30

                c.drawString(50, y, "-" * 50)
                y -= 15

                c.drawString(50, y, "Statistika za sva skladista:")
                y -= 15
                c.drawString(50, y, f"Ukupni iznos svih proizvoda iznosi: {sum_of_all_products} kn.")
                y -= 15
                c.drawString(50, y, f"Ukupno stavki: {total_items}")
                y -= 15
                c.drawString(50, y, f"Ukupno proizvoda: {total_products} kom")
                y -= 30

                c.save()
                self.master_detail_data = filename
                print("Master-detail report completed.")
        # functions that fetches data from database and generates PDF report of images
        def get_image_data(self):
            
            rows = get_image_for_pdf()
    
            output_directory = "reports/image_pdf_reports"
            
            # Create the output directory if it doesn't exist
            if not os.path.exists(output_directory):
                os.makedirs(output_directory)

            pdf_filename = os.path.join(output_directory, f"{datetime.now().strftime('%Y-%m-%d_%H-%M-%S')}_image_report.pdf")
            c = canvas.Canvas(pdf_filename, pagesize = A4)
            
            # Add the title and date at the beginning of the PDF
            title = "PDF izvjestaj slika iz tablice proizvodi"
            current_date = "Datum: 2023-08-13"  # Replace this with the actual current date
            
            c.setFont("Helvetica-Bold", 14)
            c.drawString(100, A4[1] - 50, title)
            c.setFont("Helvetica", 12)
            c.drawString(100, A4[1] - 70, current_date)
            
            y_position = A4[1] - 100
            
            for index, (product_name, image_data) in enumerate(rows):
                # Save the image data to a temporary file
                temp_image_path = f"temp_image_{index}.jpg"
                with open(temp_image_path, 'wb') as temp_image_file:
                    temp_image_file.write(image_data)
                
                image = Image.open(temp_image_path)
                
                # Scale the image while maintaining its aspect ratio
                max_width = 400  # Adjust as needed
                max_height = 300  # Adjust as needed
                image.thumbnail((max_width, max_height))
                
                # Draw product name
                c.setFont("Helvetica-Bold", 12)
                c.drawString(100, y_position, product_name)
                y_position -= 20
                
                # Draw image
                img_width, img_height = image.size
                c.drawImage(temp_image_path, 100, y_position - img_height, width=img_width, height=img_height)
                y_position -= img_height + 20
                
                # Close the image
                image.close()
                
                # Delete the temporary image file
                os.remove(temp_image_path)
            
            c.save()
            print("Image PDF report completed.")
    
    # Class for multithreading with threadpool
    class ParallelTaskExecutor:
        def __init__(self, max_workers):
            self.max_workers = max_workers
            self.executor = concurrent.futures.ThreadPoolExecutor(self.max_workers)
        
        def _run_task(self, task_func):
            task_name = task_func.__name__
            print(f"{task_name} started at {datetime.now().strftime('%H:%M:%S.%f')}")
            start_time = time.time()
            task_func()
            end_time = time.time()
            print(f"{task_name} finished at {datetime.now().strftime('%H:%M:%S.%f')}, Duration: {end_time - start_time:.2f} seconds")
        
        def run_tasks(self, tasks):
            future_results = []
            for task in tasks:
                future = self.executor.submit(self._run_task, task)
                future_results.append(future)
            
            concurrent.futures.wait(future_results)
        
        def shutdown(self):
            self.executor.shutdown()

    class UIComponentRefresh(QThread):
        
        total_cost_refesh_timer = 0
        
        update_signal_time = pyqtSignal(str)
        update_singal_date = pyqtSignal(str)
        update_singal_refresh_time = pyqtSignal(str)
        update_signal_product_cost_sum = pyqtSignal(str)
        
        def __init__(self, custom_function):
            super().__init__()
            self.custom_function = custom_function      
        
        def run(self):
            while True:
                if self.total_cost_refesh_timer == 0:
                    refresh_time = time.strftime("%H:%M:%S")
                    self.update_singal_refresh_time.emit(refresh_time)
                
                    if self.custom_function:
                        custom_result = self.custom_function()
                        self.update_signal_product_cost_sum.emit(str(custom_result))
                        
                    self.total_cost_refesh_timer = 10
                
                current_time = time.strftime("%H:%M:%S")
                current_date = time.strftime("%Y-%m-%d")
                self.update_signal_time.emit(current_time)
                self.update_singal_date.emit(current_date)
                time.sleep(1)
                self.total_cost_refesh_timer -= 1

    def setupUi(self, MainWindow, selected_language, signed_user):
        print()
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1300, 863)
        self.MainWindow = MainWindow
        self.centralwidget = QtWidgets.QWidget(parent = MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        ''' '''
        self.selected_language = selected_language
        self.signed_user = signed_user
        print(f"From main_form.py class lang: {self.selected_language}, user: {self.signed_user} !!!")

        ''' table table - prikazuje joinanu tablicu skladista i proizvodi po ID-u - lijeva tablica na GUIu '''
        self.table_proizvodi = QtWidgets.QTableWidget(parent = self.centralwidget)
        self.table_proizvodi.setGeometry(QtCore.QRect(30, 410, 691, 201))
        self.table_proizvodi.setObjectName("table_proizvodi")
        self.table_proizvodi.setColumnCount(0)
        self.table_proizvodi.setRowCount(0)
        # klickom na header tablice pokrece se sort_table funkcija
        self.table_proizvodi.horizontalHeader().sectionClicked.connect(self.sort_table)
        self.sort_order = QtCore.Qt.SortOrder.AscendingOrder
        # liste u koju funkcija 'get_table' iz modula 'access_connector' sprema podatke o
        # podatke tablici i headeru tablice
        self.table_proizvodi_array = None
        self.header = None
        # liste u koju funkcija 'get_table_by_filter' iz modula 'access_connector' sprema podatke o
        # podatke tablici i headeru tablice po unesenom filteru u edit box
        self.table_filter_array = None
        self.table_filter_header = None

        ''' group box information - prikaz active language, active user, date, time '''
        self.group_box_information = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.group_box_information.setGeometry(QtCore.QRect(10, 10, 311, 71))
        self.group_box_information.setObjectName("group_box_information")
        # label - pokazuje aktivan jezik ()
        self.label_active_language_show = QtWidgets.QLabel(parent=self.group_box_information)
        self.label_active_language_show.setGeometry(QtCore.QRect(80, 40, 47, 21))
        self.label_active_language_show.setObjectName("label_active_language_show")
        self.label_active_language_show.setText(str(self.selected_language))

        self.label_active_user = QtWidgets.QLabel(parent=self.group_box_information)
        self.label_active_user.setGeometry(QtCore.QRect(10, 20, 91, 21))
        self.label_active_user.setObjectName("label_active_user")
        # label - pokazuje aktivnog usera (user koji se logirao u aplikaciju)
        self.label_active_user_show = QtWidgets.QLabel(parent=self.group_box_information)
        self.label_active_user_show.setGeometry(QtCore.QRect(80, 20, 47, 21))
        self.label_active_user_show.setObjectName("label_active_user_show")
        self.label_active_user_show.setText(str(self.signed_user))

        self.label_active_language = QtWidgets.QLabel(parent=self.group_box_information)
        self.label_active_language.setGeometry(QtCore.QRect(10, 40, 91, 21))
        self.label_active_language.setObjectName("label_active_language")
        
        # label date and time
        self.label_date = QtWidgets.QLabel(parent=self.group_box_information)
        self.label_date.setGeometry(QtCore.QRect(180, 20, 31, 21))
        self.label_date.setObjectName("label_date")
        self.label_time_show = QtWidgets.QLabel(parent=self.group_box_information)
        self.label_time_show.setGeometry(QtCore.QRect(220, 40, 71, 21))
        self.label_time_show.setObjectName("label_time_show")
        self.label_date_show = QtWidgets.QLabel(parent=self.group_box_information)
        self.label_date_show.setGeometry(QtCore.QRect(220, 20, 71, 21))
        self.label_date_show.setObjectName("label_date_show")
        self.label_time = QtWidgets.QLabel(parent=self.group_box_information)
        self.label_time.setGeometry(QtCore.QRect(180, 40, 31, 21))
        self.label_time.setObjectName("label_time")
        # functions to auto update labels Date and Time

        
        ''' groupbox selectedd warehouse '''
        self.group_box_selected_warehouse = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.group_box_selected_warehouse.setGeometry(QtCore.QRect(10, 100, 300, 243))
        self.group_box_selected_warehouse.setObjectName("group_box_selected_warehouse")
        self.label_warehouse_information_id = QtWidgets.QLabel(parent=self.group_box_selected_warehouse)
        self.label_warehouse_information_id.setGeometry(QtCore.QRect(20, 40, 111, 16))
        self.label_warehouse_information_id.setObjectName("label_warehouse_information_id")
        self.label_warehouse_information_id_show = QtWidgets.QLabel(parent=self.group_box_selected_warehouse)
        self.label_warehouse_information_id_show.setGeometry(QtCore.QRect(140, 40, 141, 16))
        self.label_warehouse_information_id_show.setObjectName("label_warehouse_information_id_show")
        self.label_warehouse_information_name = QtWidgets.QLabel(parent=self.group_box_selected_warehouse)
        self.label_warehouse_information_name.setGeometry(QtCore.QRect(20, 60, 111, 16))
        self.label_warehouse_information_name.setObjectName("label_warehouse_information_name")
        self.label_warehouse_information_name_show = QtWidgets.QLabel(parent=self.group_box_selected_warehouse)
        self.label_warehouse_information_name_show.setGeometry(QtCore.QRect(140, 60, 141, 16))
        self.label_warehouse_information_name_show.setObjectName("label_warehouse_information_name_show")
        self.label_warehouse_information_street_show = QtWidgets.QLabel(parent=self.group_box_selected_warehouse)
        self.label_warehouse_information_street_show.setGeometry(QtCore.QRect(140, 80, 131, 16))
        self.label_warehouse_information_street_show.setObjectName("label_warehouse_information_street_show")
        self.label_warehouse_information_city_show = QtWidgets.QLabel(parent=self.group_box_selected_warehouse)
        self.label_warehouse_information_city_show.setGeometry(QtCore.QRect(140, 100, 131, 16))
        self.label_warehouse_information_city_show.setObjectName("label_warehouse_information_city_show")
        self.label_warehouse_information_city = QtWidgets.QLabel(parent=self.group_box_selected_warehouse)
        self.label_warehouse_information_city.setGeometry(QtCore.QRect(20, 100, 111, 16))
        self.label_warehouse_information_city.setObjectName("label_warehouse_information_city")
        self.label_warehouse_information_street = QtWidgets.QLabel(parent=self.group_box_selected_warehouse)
        self.label_warehouse_information_street.setGeometry(QtCore.QRect(20, 80, 111, 16))
        self.label_warehouse_information_street.setObjectName("label_warehouse_information_street")
        self.label_warehouse_information_country_show = QtWidgets.QLabel(parent=self.group_box_selected_warehouse)
        self.label_warehouse_information_country_show.setGeometry(QtCore.QRect(140, 120, 141, 16))
        self.label_warehouse_information_country_show.setObjectName("label_warehouse_information_country_show")
        self.label_warehouse_information_country = QtWidgets.QLabel(parent=self.group_box_selected_warehouse)
        self.label_warehouse_information_country.setGeometry(QtCore.QRect(20, 120, 111, 16))
        self.label_warehouse_information_country.setObjectName("label_warehouse_information_country")
        self.push_button_select_warehouse = QtWidgets.QPushButton(parent=self.group_box_selected_warehouse)
        self.push_button_select_warehouse.setGeometry(QtCore.QRect(20, 180, 151, 23))
        self.push_button_select_warehouse.setObjectName("push_button_select_warehouse")
        # funkcija kada se klikne na button poziva funkciju table_show_data
        self.push_button_select_warehouse.clicked.connect(self.table_show_data) 
        
        self.line_edit_select_warehouse = QtWidgets.QLineEdit(parent=self.group_box_selected_warehouse)
        self.line_edit_select_warehouse.setGeometry(QtCore.QRect(20, 150, 151, 20))
        self.line_edit_select_warehouse.setObjectName("line_edit_select_warehouse")

        ''' table show warehouse and products - desna tablica na GUIu ''' 
        self.table_show_warehouse_products = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.table_show_warehouse_products.setGeometry(QtCore.QRect(750, 410, 531, 201))
        self.table_show_warehouse_products.setObjectName("table_show_warehouse_products")
        self.table_show_warehouse_products.setColumnCount(0)
        self.table_show_warehouse_products.setRowCount(0)
        self.table_show_warehouse_products.horizontalHeader().sectionClicked.connect(self.sort_table_warehouse_products)
        # array u koji se sprema tablica warehouse/products
        self.table_show_warehouse_products_array = None
        self.table_show_warehouse_products_header = None
        #button za prikaz tablice produkti
        self.button_show_products = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_show_products.setGeometry(QtCore.QRect(750, 370, 251, 23))
        self.button_show_products.setObjectName("button_show_products")
        self.button_show_products.clicked.connect(self.show_products)
        #button za prikaz tablice skladiste
        self.button_show_warehouses = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_show_warehouses.setGeometry(QtCore.QRect(1030, 370, 251, 23))
        self.button_show_warehouses.setObjectName("button_show_warehouses")
        # button button_find_warehouse_by_product
        self.button_show_warehouses.clicked.connect(self.show_warehouses)

        
        self.button_find_warehouse_by_product = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_find_warehouse_by_product.setGeometry(QtCore.QRect(40, 370, 91, 23))
        self.button_find_warehouse_by_product.setObjectName("button_find_warehouse_by_product")
        # klikom na button 'Find' poziva se funkcija koja ispisuje u tablicu proizvode koji
        # matchaju filter, ako ne ostaje ispisana zadnja tablica koja se ucitala u widget
        self.button_find_warehouse_by_product.clicked.connect(self.table_show_data_filter)
        self.edit_find_warehouse_by_product = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.edit_find_warehouse_by_product.setGeometry(QtCore.QRect(140, 370, 181, 20))
        self.edit_find_warehouse_by_product.setObjectName("edit_find_warehouse_by_product")
        self.label_find_warehouse_by_prodcut_name = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_find_warehouse_by_prodcut_name.setGeometry(QtCore.QRect(40, 350, 281, 16))
        self.label_find_warehouse_by_prodcut_name.setObjectName("label_find_warehouse_by_prodcut_name")
        
        ''' groupbox delete warehouse and product '''
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(970, 100, 300, 241))
        self.groupBox.setObjectName("group_delete_warehouse_product")
        self.label_delete_warehouse = QtWidgets.QLabel(parent=self.groupBox)
        self.label_delete_warehouse.setGeometry(QtCore.QRect(20, 40, 261, 20))
        self.label_delete_warehouse.setObjectName("label_delete_warehouse")
        self.label_delete_products = QtWidgets.QLabel(parent=self.groupBox)
        self.label_delete_products.setGeometry(QtCore.QRect(20, 140, 261, 20))
        self.label_delete_products.setObjectName("label_delete_products")
        #button delete warehouse
        self.button_delete_warehouse = QtWidgets.QPushButton(parent=self.groupBox)
        self.button_delete_warehouse.setGeometry(QtCore.QRect(20, 100, 251, 23))
        self.button_delete_warehouse.setObjectName("button_delete_warehouse")
        self.button_delete_warehouse.clicked.connect(self.delete_warehouse)
        self.edit_delete_warehouse = QtWidgets.QLineEdit(parent=self.groupBox)
        self.edit_delete_warehouse.setGeometry(QtCore.QRect(20, 70, 251, 20))
        self.edit_delete_warehouse.setObjectName("edit_delete_warehouse")
        self.edit_delete_products = QtWidgets.QLineEdit(parent=self.groupBox)
        self.edit_delete_products.setGeometry(QtCore.QRect(20, 170, 251, 20))
        self.edit_delete_products.setObjectName("edit_delete_products")
        self.button_delete_product = QtWidgets.QPushButton(parent=self.groupBox)
        self.button_delete_product.setGeometry(QtCore.QRect(20, 200, 251, 23))
        self.button_delete_product.setObjectName("button_delete_product")
        self.button_delete_product.clicked.connect(self.delete_product)
        
        ''' tab warehouse '''
        self.tab_warehouse = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tab_warehouse.setGeometry(QtCore.QRect(330, 90, 300, 251))
        self.tab_warehouse.setObjectName("tab_warehouse")
        self.tab_add_warehouse = QtWidgets.QWidget()
        self.tab_add_warehouse.setObjectName("tab_add_warehouse")
        # label and edit field - warehouse name
        self.label_warehouse_name = QtWidgets.QLabel(parent=self.tab_add_warehouse)
        self.label_warehouse_name.setGeometry(QtCore.QRect(20, 20, 101, 20))
        self.label_warehouse_name.setObjectName("label_warehouse_name")
        self.line_edit_warehoue_name = QtWidgets.QLineEdit(parent=self.tab_add_warehouse)
        self.line_edit_warehoue_name.setGeometry(QtCore.QRect(130, 20, 151, 20))
        self.line_edit_warehoue_name.setObjectName("line_edit_warehoue_name")
        # label and edit field - warehouse street  
        self.label_warehouse_street = QtWidgets.QLabel(parent=self.tab_add_warehouse)
        self.label_warehouse_street.setGeometry(QtCore.QRect(20, 50, 101, 21))
        self.label_warehouse_street.setObjectName("label_warehouse_street")
        self.line_edit_warehoue_street = QtWidgets.QLineEdit(parent=self.tab_add_warehouse)
        self.line_edit_warehoue_street.setGeometry(QtCore.QRect(130, 50, 151, 20))
        self.line_edit_warehoue_street.setObjectName("line_edit_warehoue_street")
        # label and edit field - warehouse city  
        self.line_edit_warehoue_city = QtWidgets.QLineEdit(parent=self.tab_add_warehouse)
        self.line_edit_warehoue_city.setGeometry(QtCore.QRect(130, 80, 151, 20))
        self.line_edit_warehoue_city.setObjectName("line_edit_warehoue_city")
        self.label_warehouse_city = QtWidgets.QLabel(parent=self.tab_add_warehouse)
        self.label_warehouse_city.setGeometry(QtCore.QRect(20, 80, 101, 20))
        self.label_warehouse_city.setObjectName("label_warehouse_city")
        # label and edit field - warehouse country 
        self.label_warehouse_country = QtWidgets.QLabel(parent=self.tab_add_warehouse)
        self.label_warehouse_country.setGeometry(QtCore.QRect(20, 110, 101, 20))
        self.label_warehouse_country.setObjectName("label_warehouse_country")
        self.line_edit_warehoue_country = QtWidgets.QLineEdit(parent=self.tab_add_warehouse)
        self.line_edit_warehoue_country.setGeometry(QtCore.QRect(130, 110, 151, 20))
        self.line_edit_warehoue_country.setObjectName("line_edit_warehoue_country")
        # button save warehouse
        self.button_save_warehouse = QtWidgets.QPushButton(parent=self.tab_add_warehouse)
        self.button_save_warehouse.setGeometry(QtCore.QRect(20, 150, 261, 23))
        self.button_save_warehouse.setObjectName("button_save_warehouse")
        # button poziva funkciju add_to_database_warehouse
        self.button_save_warehouse.clicked.connect(self.add_to_database_warehouse)
        
        
        # tab edit warehouse
        self.tab_warehouse.addTab(self.tab_add_warehouse, "")
        self.tab_edit_warehouse = QtWidgets.QWidget()
        self.tab_edit_warehouse.setObjectName("tab_edit_warehouse")
        self.label_warehouse_city_edit = QtWidgets.QLabel(parent=self.tab_edit_warehouse)
        self.label_warehouse_city_edit.setGeometry(QtCore.QRect(20, 100, 101, 20))
        self.label_warehouse_city_edit.setObjectName("label_warehouse_city_edit")
        self.label_warehouse_street_edit = QtWidgets.QLabel(parent=self.tab_edit_warehouse)
        self.label_warehouse_street_edit.setGeometry(QtCore.QRect(20, 70, 101, 21))
        self.label_warehouse_street_edit.setObjectName("label_warehouse_street_edit")
        self.label_warehouse_name_edit = QtWidgets.QLabel(parent=self.tab_edit_warehouse)
        self.label_warehouse_name_edit.setGeometry(QtCore.QRect(20, 40, 101, 20))
        self.label_warehouse_name_edit.setObjectName("label_warehouse_name_edit")
        # button koji na click poziva funkciju <blank> koja mijenja value warehouse u databazi
        self.button_edit_warehouse = QtWidgets.QPushButton(parent=self.tab_edit_warehouse)
        self.button_edit_warehouse.setGeometry(QtCore.QRect(20, 170, 261, 23))
        self.button_edit_warehouse.setObjectName("button_edit_warehouse")
        self.button_edit_warehouse.clicked.connect(self.change_warehouse_values)
        self.line_edit_warehoue_city_edit = QtWidgets.QLineEdit(parent=self.tab_edit_warehouse)
        self.line_edit_warehoue_city_edit.setGeometry(QtCore.QRect(130, 100, 151, 20))
        self.line_edit_warehoue_city_edit.setObjectName("line_edit_warehoue_city_edit")
        self.line_edit_warehoue_street_edit = QtWidgets.QLineEdit(parent=self.tab_edit_warehouse)
        self.line_edit_warehoue_street_edit.setGeometry(QtCore.QRect(130, 70, 151, 20))
        self.line_edit_warehoue_street_edit.setObjectName("line_edit_warehoue_street_edit")
        self.line_edit_warehoue_name_edit = QtWidgets.QLineEdit(parent=self.tab_edit_warehouse)
        self.line_edit_warehoue_name_edit.setGeometry(QtCore.QRect(130, 40, 151, 20))
        self.line_edit_warehoue_name_edit.setObjectName("line_edit_warehoue_name_edit")
        self.label_warehouse_country_edit = QtWidgets.QLabel(parent=self.tab_edit_warehouse)
        self.label_warehouse_country_edit.setGeometry(QtCore.QRect(20, 130, 101, 20))
        self.label_warehouse_country_edit.setObjectName("label_warehouse_country_edit")
        self.line_edit_warehoue_country_edit = QtWidgets.QLineEdit(parent=self.tab_edit_warehouse)
        self.line_edit_warehoue_country_edit.setGeometry(QtCore.QRect(130, 130, 151, 20))
        self.line_edit_warehoue_country_edit.setObjectName("line_edit_warehoue_country_edit")
        self.label_warehouse_id_edit = QtWidgets.QLabel(parent=self.tab_edit_warehouse)
        self.label_warehouse_id_edit.setGeometry(QtCore.QRect(20, 10, 101, 20))
        self.label_warehouse_id_edit.setObjectName("label_warehouse_id_edit")
        self.line_edit_warehoue_name_id_edit = QtWidgets.QLineEdit(parent=self.tab_edit_warehouse)
        self.line_edit_warehoue_name_id_edit.setGeometry(QtCore.QRect(130, 10, 151, 20))
        self.line_edit_warehoue_name_id_edit.setObjectName("line_edit_warehoue_name_id_edit")
        self.tab_warehouse.addTab(self.tab_edit_warehouse, "")
        
        ''' tab products '''
        self.tab_products = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tab_products.setGeometry(QtCore.QRect(650, 90, 300, 251))
        self.tab_products.setObjectName("tab_products")
        
        ''' tab add products '''
        self.tab_add_product = QtWidgets.QWidget()
        self.tab_add_product.setObjectName("tab_add_product")
        self.line_edit_products_warehouse_id = QtWidgets.QLineEdit(parent=self.tab_add_product)
        self.line_edit_products_warehouse_id.setGeometry(QtCore.QRect(100, 20, 181, 20))
        self.line_edit_products_warehouse_id.setObjectName("line_edit_products_warehouse_id")
        self.label_product_warehouse_id = QtWidgets.QLabel(parent=self.tab_add_product)
        self.label_product_warehouse_id.setGeometry(QtCore.QRect(20, 20, 71, 20))
        self.label_product_warehouse_id.setObjectName("label_product_warehouse_id")
        self.line_edit_products_quantity = QtWidgets.QLineEdit(parent=self.tab_add_product)
        self.line_edit_products_quantity.setGeometry(QtCore.QRect(100, 110, 181, 20))
        self.line_edit_products_quantity.setObjectName("line_edit_products_quantity")
        self.line_edit_products_category = QtWidgets.QLineEdit(parent=self.tab_add_product)
        self.line_edit_products_category.setGeometry(QtCore.QRect(100, 140, 181, 20))
        self.line_edit_products_category.setObjectName("line_edit_products_category")
        self.label_product_name = QtWidgets.QLabel(parent=self.tab_add_product)
        self.label_product_name.setGeometry(QtCore.QRect(20, 50, 71, 21))
        self.label_product_name.setObjectName("label_product_name")
        self.label_product_quantity = QtWidgets.QLabel(parent=self.tab_add_product)
        self.label_product_quantity.setGeometry(QtCore.QRect(20, 110, 71, 21))
        self.label_product_quantity.setScaledContents(False)
        self.label_product_quantity.setWordWrap(False)
        self.label_product_quantity.setObjectName("label_product_quantity")
        self.line_edit_products_name = QtWidgets.QLineEdit(parent=self.tab_add_product)
        self.line_edit_products_name.setGeometry(QtCore.QRect(100, 50, 181, 20))
        self.line_edit_products_name.setObjectName("line_edit_products_name")
        self.button_save_product = QtWidgets.QPushButton(parent=self.tab_add_product)
        self.button_save_product.setGeometry(QtCore.QRect(20, 170, 261, 23))
        self.button_save_product.setObjectName("button_save_product")
        
        # button koji na klick poziva funkciju add_to_database_products 
        self.button_save_product.clicked.connect(self.add_to_database_products)
        self.line_edit_products_price = QtWidgets.QLineEdit(parent=self.tab_add_product)
        self.line_edit_products_price.setGeometry(QtCore.QRect(100, 80, 181, 20))
        self.line_edit_products_price.setObjectName("line_edit_products_price")
        self.label_product_category = QtWidgets.QLabel(parent=self.tab_add_product)
        self.label_product_category.setGeometry(QtCore.QRect(20, 140, 71, 21))
        self.label_product_category.setScaledContents(False)
        self.label_product_category.setWordWrap(False)
        self.label_product_category.setObjectName("label_product_category")
        self.label_product_price = QtWidgets.QLabel(parent=self.tab_add_product)
        self.label_product_price.setGeometry(QtCore.QRect(20, 80, 71, 21))
        self.label_product_price.setObjectName("label_product_price")
        
        # tab edit products
        self.tab_products.addTab(self.tab_add_product, "")
        self.tab_edit_product = QtWidgets.QWidget()
        self.tab_edit_product.setObjectName("tab_edit_product")
        self.label_product_name_edit = QtWidgets.QLabel(parent=self.tab_edit_product)
        self.label_product_name_edit.setGeometry(QtCore.QRect(20, 70, 71, 21))
        self.label_product_name_edit.setObjectName("label_product_name_edit")
        self.label_product_price_edit = QtWidgets.QLabel(parent=self.tab_edit_product)
        self.label_product_price_edit.setGeometry(QtCore.QRect(20, 100, 71, 21))
        self.label_product_price_edit.setObjectName("label_product_price_edit")
        self.label_product_warehouse_id_edit = QtWidgets.QLabel(parent=self.tab_edit_product)
        self.label_product_warehouse_id_edit.setGeometry(QtCore.QRect(20, 40, 71, 20))
        self.label_product_warehouse_id_edit.setObjectName("label_product_warehouse_id_edit")
        self.label_product_quantity_edit = QtWidgets.QLabel(parent=self.tab_edit_product)
        self.label_product_quantity_edit.setGeometry(QtCore.QRect(20, 130, 71, 21))
        self.label_product_quantity_edit.setScaledContents(False)
        self.label_product_quantity_edit.setWordWrap(False)
        self.label_product_quantity_edit.setObjectName("label_product_quantity_edit")
        self.line_edit_products_price_edit = QtWidgets.QLineEdit(parent=self.tab_edit_product)
        self.line_edit_products_price_edit.setGeometry(QtCore.QRect(100, 100, 181, 20))
        self.line_edit_products_price_edit.setObjectName("line_edit_products_price_edit")
        self.label_product_category_edit = QtWidgets.QLabel(parent=self.tab_edit_product)
        self.label_product_category_edit.setGeometry(QtCore.QRect(20, 160, 71, 21))
        self.label_product_category_edit.setScaledContents(False)
        self.label_product_category_edit.setWordWrap(False)
        self.label_product_category_edit.setObjectName("label_product_category_edit")
        self.line_edit_products_category_edit = QtWidgets.QLineEdit(parent=self.tab_edit_product)
        self.line_edit_products_category_edit.setGeometry(QtCore.QRect(100, 160, 181, 20))
        self.line_edit_products_category_edit.setObjectName("line_edit_products_category_edit")
        self.line_edit_products_quantity_edit = QtWidgets.QLineEdit(parent=self.tab_edit_product)
        self.line_edit_products_quantity_edit.setGeometry(QtCore.QRect(100, 130, 181, 20))
        self.line_edit_products_quantity_edit.setObjectName("line_edit_products_quantity_edit")
        
        # button koji na click poziva funkciju 'change_product_values'
        self.button_edit_products = QtWidgets.QPushButton(parent=self.tab_edit_product)
        self.button_edit_products.setGeometry(QtCore.QRect(20, 190, 261, 23))
        self.button_edit_products.setObjectName("button_edit_products")
        self.button_edit_products.clicked.connect(self.change_product_values)
        
        self.line_edit_products_name_edit = QtWidgets.QLineEdit(parent=self.tab_edit_product)
        self.line_edit_products_name_edit.setGeometry(QtCore.QRect(100, 70, 181, 20))
        self.line_edit_products_name_edit.setObjectName("line_edit_products_name_edit")
        self.line_edit_products_warehouse_id_edit = QtWidgets.QLineEdit(parent=self.tab_edit_product)
        self.line_edit_products_warehouse_id_edit.setGeometry(QtCore.QRect(100, 40, 181, 20))
        self.line_edit_products_warehouse_id_edit.setObjectName("line_edit_products_warehouse_id_edit")
        self.label_product_id_edit = QtWidgets.QLabel(parent=self.tab_edit_product)
        self.label_product_id_edit.setGeometry(QtCore.QRect(20, 10, 71, 20))
        self.label_product_id_edit.setObjectName("label_product_id_edit")
        self.line_edit_product_id = QtWidgets.QLineEdit(parent=self.tab_edit_product)
        self.line_edit_product_id.setGeometry(QtCore.QRect(100, 10, 181, 20))
        self.line_edit_product_id.setObjectName("line_edit_product_id")
        self.tab_products.addTab(self.tab_edit_product, "")
        
        # tab picture products - dodavanje i prikaz blob fileova - u ovom slucaju slika produkata
        self.tab_picture_product = QtWidgets.QWidget()
        self.tab_picture_product.setObjectName("tab_picture_product")
        self.labela_add_picture_id = QtWidgets.QLabel(parent=self.tab_picture_product)
        self.labela_add_picture_id.setGeometry(QtCore.QRect(20, 20, 251, 21))
        self.labela_add_picture_id.setObjectName("labela_add_picture_id")
        self.edit_add_picture_id = QtWidgets.QLineEdit(parent=self.tab_picture_product)
        self.edit_add_picture_id.setGeometry(QtCore.QRect(20, 50, 251, 20))
        self.edit_add_picture_id.setObjectName("edit_add_picture_id")
        
        # button za odabit slike lokalno sa PC-a
        self.button_select_picture = QtWidgets.QPushButton(parent=self.tab_picture_product)
        self.button_select_picture.setGeometry(QtCore.QRect(20, 80, 121, 23))
        self.button_select_picture.setObjectName("button_select_picture")
        self.button_select_picture.clicked.connect(self.load_picture)
        # privremena varijabla za 
        self.temp_blob_variable = None
        # button na klick otvara novu formu za prikaz slike
        self.button_save_picture = QtWidgets.QPushButton(parent=self.tab_picture_product)
        self.button_save_picture.setGeometry(QtCore.QRect(150, 80, 121, 23))
        self.button_save_picture.setObjectName("button_save_picture")
        self.button_save_picture.clicked.connect(self.save_picture_to_database)
        
        self.label_file_name = QtWidgets.QLabel(parent=self.tab_picture_product)
        self.label_file_name.setGeometry(QtCore.QRect(20, 110, 111, 20))
        self.label_file_name.setObjectName("label_file_name")
        self.label_file_name_show = QtWidgets.QLabel(parent=self.tab_picture_product)
        self.label_file_name_show.setGeometry(QtCore.QRect(146, 110, 121, 20))
        self.label_file_name_show.setObjectName("label_file_name_show")
        self.label_show_picture_id = QtWidgets.QLabel(parent=self.tab_picture_product)
        self.label_show_picture_id.setGeometry(QtCore.QRect(20, 140, 251, 16))
        self.label_show_picture_id.setObjectName("label_show_picture_id")
        self.edit_show_picture_id = QtWidgets.QLineEdit(parent=self.tab_picture_product)
        self.edit_show_picture_id.setGeometry(QtCore.QRect(20, 170, 113, 20))
        self.edit_show_picture_id.setObjectName("lineEdit")
        self.button_show_picture = QtWidgets.QPushButton(parent=self.tab_picture_product)
        self.button_show_picture.setGeometry(QtCore.QRect(150, 170, 121, 23))
        self.button_show_picture.setObjectName("button_show_picture")
        self.button_show_picture.clicked.connect(self.show_picture)
        self.tab_products.addTab(self.tab_picture_product, "")
        MainWindow.setCentralWidget(self.centralwidget)

        """ Groupbox Reports """
        # groupbox "Reports" on the GUI
        self.group_box_reports = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.group_box_reports.setGeometry(QtCore.QRect(30, 630, 171, 101))
        self.group_box_reports.setObjectName("group_box_reports")
        # button "Generate reports" on the GUI
        self.button_generate_reports = QtWidgets.QPushButton(parent=self.group_box_reports)
        self.button_generate_reports.setGeometry(QtCore.QRect(20, 60, 131, 23))
        self.button_generate_reports.setObjectName("button_generate_reports")
        self.button_generate_reports.clicked.connect(self.generate_reports)
        # button "Show reports" on the GUI
        self.button_show_reports = QtWidgets.QPushButton(parent=self.group_box_reports)
        self.button_show_reports.setGeometry(QtCore.QRect(20, 30, 131, 23))
        self.button_show_reports.setObjectName("button_show_reports")
        self.button_show_reports.clicked.connect(self.show_report_form)
        
        """ Groupbox Total cost of all products  """
        self.groupBox_total_cost = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_total_cost.setGeometry(QtCore.QRect(750, 620, 531, 61))
        self.groupBox_total_cost.setObjectName("groupBox_total_cost")
        self.label_refresh = QtWidgets.QLabel(parent=self.groupBox_total_cost)
        self.label_refresh.setGeometry(QtCore.QRect(10, 20, 151, 16))
        self.label_refresh.setObjectName("label_refresh")
        self.label_refresh_time = QtWidgets.QLabel(parent=self.groupBox_total_cost)
        self.label_refresh_time.setGeometry(QtCore.QRect(170, 20, 151, 16))
        self.label_refresh_time.setText("")
        self.label_refresh_time.setObjectName("label_refresh_time")
        self.label_sum_product_price = QtWidgets.QLabel(parent=self.groupBox_total_cost)
        self.label_sum_product_price.setGeometry(QtCore.QRect(10, 40, 151, 16))
        self.label_sum_product_price.setObjectName("label_sum_product_price")
        self.label_sum_product_price_show = QtWidgets.QLabel(parent=self.groupBox_total_cost)
        self.label_sum_product_price_show.setGeometry(QtCore.QRect(170, 40, 131, 16))
        self.label_sum_product_price_show.setText("")
        self.label_sum_product_price_show.setObjectName("label_sum_product_price_show")
        
        """ Groupbox Total product price in other currencies"""
        self.groupBox_exchange_rate = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_exchange_rate.setGeometry(QtCore.QRect(750, 690, 531, 151))
        self.groupBox_exchange_rate.setObjectName("groupBox")
        self.label_eur = QtWidgets.QLabel(parent=self.groupBox_exchange_rate)
        self.label_eur.setGeometry(QtCore.QRect(20, 20, 47, 13))
        self.label_eur.setObjectName("label_eur")
        self.label_eur_show = QtWidgets.QLabel(parent=self.groupBox_exchange_rate)
        self.label_eur_show.setGeometry(QtCore.QRect(80, 20, 47, 13))
        self.label_eur_show.setObjectName("label_eur_show")
        self.label_usd = QtWidgets.QLabel(parent=self.groupBox_exchange_rate)
        self.label_usd.setGeometry(QtCore.QRect(20, 40, 47, 13))
        self.label_usd.setObjectName("label_usd")
        self.label_usd_show = QtWidgets.QLabel(parent=self.groupBox_exchange_rate)
        self.label_usd_show.setGeometry(QtCore.QRect(80, 40, 47, 13))
        self.label_usd_show.setObjectName("label_usd_show")
        self.label_cad = QtWidgets.QLabel(parent=self.groupBox_exchange_rate)
        self.label_cad.setGeometry(QtCore.QRect(20, 60, 47, 13))
        self.label_cad.setObjectName("label_cad")
        self.label_cad_show = QtWidgets.QLabel(parent=self.groupBox_exchange_rate)
        self.label_cad_show.setGeometry(QtCore.QRect(80, 60, 47, 13))
        self.label_cad_show.setObjectName("label_cad_show")
        self.label_aud = QtWidgets.QLabel(parent=self.groupBox_exchange_rate)
        self.label_aud.setGeometry(QtCore.QRect(20, 80, 47, 13))
        self.label_aud.setObjectName("label_aud")
        self.label_aud_show = QtWidgets.QLabel(parent=self.groupBox_exchange_rate)
        self.label_aud_show.setGeometry(QtCore.QRect(80, 80, 47, 13))
        self.label_aud_show.setObjectName("label_aud_show")
        self.label_gbp_show = QtWidgets.QLabel(parent=self.groupBox_exchange_rate)
        self.label_gbp_show.setGeometry(QtCore.QRect(80, 100, 47, 13))
        self.label_gbp_show.setObjectName("label_gbp_show")
        self.label_gbp = QtWidgets.QLabel(parent=self.groupBox_exchange_rate)
        self.label_gbp.setGeometry(QtCore.QRect(20, 100, 47, 13))
        self.label_gbp.setObjectName("label_gbp")
        self.button_convert_currencies = QtWidgets.QPushButton(parent=self.groupBox_exchange_rate)
        self.button_convert_currencies.setGeometry(QtCore.QRect(20, 120, 101, 23))
        self.button_convert_currencies.setObjectName("button_convert_currencies")
        
        self.retranslateUi(MainWindow)
        
        self.refresh_thread = Ui_MainWindow.UIComponentRefresh(get_product_sum)
        self.refresh_thread.update_signal_time.connect(self.update_time_label)
        self.refresh_thread.update_singal_date.connect(self.update_date_label)
        self.refresh_thread.update_singal_refresh_time.connect(self.update_refresh_time_label)
        self.refresh_thread.update_signal_product_cost_sum.connect(self.update_custom_label)
        self.refresh_thread.start()
        
        # postavlja otvorene tabove na add warehouse, and add product
        self.tab_warehouse.setCurrentIndex(0)
        self.tab_products.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        

        

    ''' Custom funkcije  '''

    def update_time_label(self, new_time):
        self.label_time_show.setText(new_time)

    def update_date_label(self, new_date):
        self.label_date_show.setText(new_date)

    def update_refresh_time_label(self, new_refresh_time):
        self.label_refresh_time.setText(new_refresh_time)

    def update_custom_label(self, custom_result):
        self.label_sum_product_price_show.setText(custom_result)
    
    # function related to button self.button_show_reports
    def generate_reports(self):
        # creating object of the class Report_Generator, so I can use Report_Generator 
        # functions and variables in class Ui_MainWindow
        
        # functions take additional argument "show", to only show report to the user
        # if that arguments was something else reports would be generated and saved localy
        # inside the project folder "reports/*"
        
        """signle thread"""
        # self.report_generator_data = Ui_MainWindow.Report_Generator
        # self.report_generator_data.get_product_data(self, "generate")
        # self.report_generator_data.get_master_detail_data(self, "generate")
        # self.report_generator_data.get_image_data(self)

        """multiple thread with threadpool"""
        self.report_generator_data = Ui_MainWindow.Report_Generator
        number_of_threads = 4
        self.threadpool = Ui_MainWindow.ParallelTaskExecutor(number_of_threads)
        list_of_tasks = [lambda: self.report_generator_data.get_image_data(self),
                         lambda: self.report_generator_data.get_master_detail_data(self, "generate"),
                         lambda: self.report_generator_data.get_product_data(self, "generate"),]
        
        self.threadpool.run_tasks(list_of_tasks)
        self.threadpool.shutdown()
        
        QtWidgets.QMessageBox.information(self.MainWindow,
                                "Reports generated successfully",
                                "Reports are saved inside folder 'reprots'.")
        
    # function related to button self.button_show_reports
    # on click calls widget report_form.py that shows databse reports
    def show_report_form(self):
        self.main_window = QtWidgets.QMainWindow()
        self.show_report = Report_Form()
        
        # object of Report_Generator class
        self.report_generator_data = Ui_MainWindow.Report_Generator
        self.report_generator_data.get_product_data(self, "show")
        self.report_generator_data.get_master_detail_data(self, "show")
        
        self.product_data, self.master_detail_data = self.report_generator_data.return_data(self)
        
        self.show_report.setupUi(self.main_window, self.product_data, self.master_detail_data)
        self.main_window.show()
    
    def save_picture_to_database(self):
        import_image(self.edit_add_picture_id.text(),
                     self.temp_blob_variable)
    
    def show_picture(self):
        self.temp_blob_variable = get_image(self.edit_show_picture_id.text())
        if self.temp_blob_variable == None:
            QtWidgets.QMessageBox.warning(self.MainWindow, "Error", f"No image found for product ID: {self.edit_show_picture_id.text()}")
            return

        self.main_window = QtWidgets.QMainWindow()
        self.show_image_form = Ui_Form()
        self.show_image_form.setupUi(self.main_window,
                                     self.temp_blob_variable)
        self.main_window.show()
    
    def load_picture(self):
        file_dialog = QtWidgets.QFileDialog()
        file_dialog.setWindowTitle("Select Image")
        file_dialog.setFileMode(QtWidgets.QFileDialog.FileMode.ExistingFile)
        file_dialog.setNameFilter("Images (*.png *.xpm *.jpg *.bmp)")
        
        if file_dialog.exec() == QtWidgets.QFileDialog.DialogCode.Accepted:
            file_path = file_dialog.selectedFiles()[0]
            file_name = file_path.split("/")[-1]
            self.label_file_name_show.setText(file_name)
            
            # Convert the image to binary file
            with open(file_path, 'rb') as image_file:
                image_data = image_file.read()
            self.temp_blob_variable = bytearray(image_data)
            
    def sort_table_warehouse_products(self, logical_index):
        # mijenja redosljed sortiranja
        
        # self.table_proizvodi_array is a list, that contains tuples for its element
        # convert tuples to the list for easy manipulation of the list
        self.new_array_table_warehouse_products = [list(x) for x in self.table_show_warehouse_products_array]
        
        # checks for the last element in the inner array, if it is None, it sets it to False, otherway True
        # also checks if it is already set to True or False, if it is, do nothing
        for inner_array in self.new_array_table_warehouse_products:
            last_element = inner_array[-1]
            if last_element is None:
                inner_array[-1] = "False"
            elif last_element == "True" or last_element == "False":
                # Do nothing, leave it unchanged if set to True or False
                pass
            elif last_element:
                inner_array[-1] = "True"          
        
        # replace old list with the new one
        self.table_show_warehouse_products_array = self.new_array_table_warehouse_products
        
        # sort the list by the logical index (Logical Index is the number of the column in the table)
        self.sort_order = QtCore.Qt.SortOrder.DescendingOrder if self.sort_order == QtCore.Qt.SortOrder.AscendingOrder else QtCore.Qt.SortOrder.AscendingOrder
        self.table_show_warehouse_products_array.sort(key = lambda x: x[logical_index], reverse = self.sort_order == QtCore.Qt.SortOrder.DescendingOrder)
        # update table with new values on the GUI
        self.update_table_warehouse_products()

    # funkcija koja se poziva nakon funkcije 'def sort_table()' te ona azurira podatke
    # u tablici 'table_proizvodi'
    
    def update_table_warehouse_products(self):
        self.table_show_warehouse_products.clear()
        self.table_show_warehouse_products.setRowCount(len(self.table_show_warehouse_products_array))
        self.table_show_warehouse_products.setColumnCount(len(self.table_show_warehouse_products_array[0]))
        self.table_show_warehouse_products.setHorizontalHeaderLabels(self.table_show_warehouse_products_header)
        
        for row, data in enumerate(self.table_show_warehouse_products_array):
            for col, value in enumerate(data):
                item = QtWidgets.QTableWidgetItem(str(value))
                self.table_show_warehouse_products.setItem(row, col, item)
      
        # Function that is called when the header of the table 'table_proizvodi' is clicked, which subsequently calls the function 'update_table()'
    def sort_table(self, logical_index):
        # mijenja redosljed sortiranja
        
        # self.table_proizvodi_array is a list, that contains tuples for its element
        # convert tuples to the list for easy manipulation of the list
        print(self.table_proizvodi_array)
        self.new_array_table_proizvodi = [list(x) for x in self.table_proizvodi_array]
        
        # checks for the last element in the inner array, if it is None, it sets it to False, otherway True
        # also checks if it is already set to True or False, if it is, do nothing
        for inner_array in self.new_array_table_proizvodi:
            last_element = inner_array[-1]
            if last_element is None:
                inner_array[-1] = "False"
            elif last_element == "True" or last_element == "False":
                # Do nothing, leave it unchanged if set to True or False
                pass
            elif last_element:
                inner_array[-1] = "True"          
        
        # replace old list with the new one
        self.table_proizvodi_array = self.new_array_table_proizvodi
        
        # sort the list by the logical index (Logical Index is the number of the column in the table)
        self.sort_order = QtCore.Qt.SortOrder.DescendingOrder if self.sort_order == QtCore.Qt.SortOrder.AscendingOrder else QtCore.Qt.SortOrder.AscendingOrder
        self.table_proizvodi_array.sort(key = lambda x: x[logical_index], reverse = self.sort_order == QtCore.Qt.SortOrder.DescendingOrder)
        # update table with new values on the GUI
        self.update_table()

    # funkcija koja se poziva nakon funkcije 'def sort_table()' te ona azurira podatke
    # u tablici 'table_proizvodi'
    def update_table(self):
        self.table_proizvodi.clear()
        self.table_proizvodi.setRowCount(len(self.table_proizvodi_array))
        self.table_proizvodi.setColumnCount(len(self.table_proizvodi_array[0]))
        self.table_proizvodi.setHorizontalHeaderLabels(self.header)
        
        for row, data in enumerate(self.table_proizvodi_array):
            for col, value in enumerate(data):
                item = QtWidgets.QTableWidgetItem(str(value))
                self.table_proizvodi.setItem(row, col, item)
            
    def table_show_data(self):     
        warehouse_id = self.line_edit_select_warehouse.text()
        
        if not warehouse_id:
            QtWidgets.QMessageBox.warning(self.MainWindow, "Error", "You need to enter warehouse id!")
            return
        
        warehouse_id = int(warehouse_id)
        # sprema tablicu 'self.table_proizvodi_array' i header tablice u self 'self.header' za
        # kasniju upotrebu kod sortiranja


        self.table_proizvodi_array, self.header, list_of_skladiste_id = get_table(warehouse_id)

        if warehouse_id not in list_of_skladiste_id:
            QtWidgets.QMessageBox.warning(self.MainWindow, "Error", "Not warehouse is not in database")
            print("Ne postji skladiste sa indexom {}".format(warehouse_id))
        else:
            
            number_of_rows = len(self.table_proizvodi_array)
            number_of_columns = len(self.table_proizvodi_array[0]) if number_of_rows > 0 else 0
            
            self.table_proizvodi.setRowCount(number_of_rows)
            self.table_proizvodi.setColumnCount(number_of_columns)
            self.table_proizvodi.setHorizontalHeaderLabels(self.header)
            
            for x, row in enumerate(self.table_proizvodi_array):
                for y, column_value in enumerate(row):
                    if column_value is None:
                        value = QtWidgets.QTableWidgetItem("False")
                    elif isinstance(column_value, bytes):
                        value = QtWidgets.QTableWidgetItem("True")
                    else:
                        value = QtWidgets .QTableWidgetItem(str(column_value))
                    self.table_proizvodi.setItem(x, y, value)
            
            if not self.table_proizvodi_array:
                QtWidgets.QMessageBox.warning(self.MainWindow, "Error", f"Warehouse by id: {warehouse_id} has no products!")
        
    def table_show_data_filter(self):
        product_filter = self.edit_find_warehouse_by_product.text()
        
        self.table_filter_array, self.table_filter_header, has_result = get_table_by_filter(product_filter)
        
        # update self.table_proizvodi_array and self.header with new values
        # so the update_table function can use them to update the table (sort)
        # on the GUI with new value for the filter table search
        self.table_proizvodi_array = self.table_filter_array
        self.header = self.table_filter_header
        
        if has_result == False:
            QtWidgets.QMessageBox.warning(self.MainWindow, "Error", "Not found in database")
        else:
            number_of_rows = len(self.table_filter_array)
            number_of_columns = len(self.table_filter_array[0]) if number_of_rows > 0 else 0
            
            self.table_proizvodi.setRowCount(number_of_rows)
            self.table_proizvodi.setColumnCount(number_of_columns)
            self.table_proizvodi.setHorizontalHeaderLabels(self.table_filter_header)
            
            for x, row in enumerate(self.table_filter_array):
                for y, column_value in enumerate(row):
                    value = QtWidgets .QTableWidgetItem(str(column_value))
                    self.table_proizvodi.setItem(x, y, value)
                

    def add_to_database_products(self):
        import_product(self.line_edit_products_warehouse_id.text(),
                        self.line_edit_products_name.text(),
                        self.line_edit_products_price.text(),
                        self.line_edit_products_quantity.text(),
                        self.line_edit_products_category.text())

    def add_to_database_warehouse(self):
        print("Add add_to_database_warehouse clicked!")
        import_warehouse(self.line_edit_warehoue_name.text(),
                         self.line_edit_warehoue_street.text(),
                         self.line_edit_warehoue_city.text(),
                         self.line_edit_warehoue_country.text())

    def change_product_values(self):
        if update_product(self.line_edit_product_id.text(),
                            self.line_edit_products_warehouse_id_edit.text(),
                            self.line_edit_products_name_edit.text(),
                            self.line_edit_products_price_edit.text(),
                            self.line_edit_products_quantity_edit.text(),
                            self.line_edit_products_category_edit.text()) == True:
            QtWidgets.QMessageBox.warning(self.MainWindow, "Success", "Product updated!")
        else:
            QtWidgets.QMessageBox.warning(self.MainWindow, "Error", "Product do not exist in database!")

    def change_warehouse_values(self):
        if update_warehouse(self.line_edit_warehoue_name_id_edit.text(),
                            self.line_edit_warehoue_name_edit.text(),
                            self.line_edit_warehoue_street_edit.text(),
                            self.line_edit_warehoue_city_edit.text(),
                            self.line_edit_warehoue_country_edit.text()) == True:
            QtWidgets.QMessageBox.warning(self.MainWindow, "Success", "Warehouse updated!")
        else:
            QtWidgets.QMessageBox.warning(self.MainWindow, "Error", "Warehouse do not exist in database!")
    
    def delete_product(self):
        if delete_product_by_id(self.edit_delete_products.text()) == True:
            QtWidgets.QMessageBox.warning(self.MainWindow, "Success", "Product deleted!")
        else:
            QtWidgets.QMessageBox.warning(self.MainWindow, "Error", f"Product with id: {self.edit_delete_products.text()} is not in database!")

    def delete_warehouse(self):
        if delete_warehouse_by_id(self.edit_delete_warehouse.text()) == True:
            QtWidgets.QMessageBox.warning(self.MainWindow, "Success", "Product deleted!")
        else:
            QtWidgets.QMessageBox.warning(self.MainWindow, "Error", f"Product with id: {self.edit_delete_warehouse.text()} is not in database!")
    
    
    def show_warehouses(self):
        self.table_show_warehouse_products_array, self.table_show_warehouse_products_header = show_table("warehouse") 
        
        number_of_rows = len(self.table_show_warehouse_products_array)
        number_of_columns = len(self.table_show_warehouse_products_array[0]) if number_of_rows > 0 else 0
            
        self.table_show_warehouse_products.setRowCount(number_of_rows)
        self.table_show_warehouse_products.setColumnCount(number_of_columns)
        self.table_show_warehouse_products.setHorizontalHeaderLabels(self.table_show_warehouse_products_header)
        
        for x, row in enumerate(self.table_show_warehouse_products_array):
            for y, column_value in enumerate(row):
                value = QtWidgets .QTableWidgetItem(str(column_value))
                self.table_show_warehouse_products.setItem(x, y, value)

    
    def show_products(self):
        self.table_show_warehouse_products_array, self.table_show_warehouse_products_header= show_table("product") 
        
        number_of_rows = len(self.table_show_warehouse_products_array)
        number_of_columns = len(self.table_show_warehouse_products_array[0]) if number_of_rows > 0 else 0
            
        self.table_show_warehouse_products.setRowCount(number_of_rows)
        self.table_show_warehouse_products.setColumnCount(number_of_columns)
        self.table_show_warehouse_products.setHorizontalHeaderLabels(self.table_show_warehouse_products_header)
        
        for x, row in enumerate(self.table_show_warehouse_products_array):
            for y, column_value in enumerate(row):
                value = QtWidgets .QTableWidgetItem(str(column_value))
                self.table_show_warehouse_products.setItem(x, y, value)
    
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.group_box_information.setTitle(_translate("MainWindow", "Information"))
        self.label_active_user.setText(_translate("MainWindow", "Active user:"))
        self.label_active_language.setText(_translate("MainWindow", "Language:"))
        self.label_date.setText(_translate("MainWindow", "Date:"))
        self.label_time_show.setText(_translate("MainWindow", "None"))
        self.label_date_show.setText(_translate("MainWindow", "None"))
        self.label_time.setText(_translate("MainWindow", "Time:"))
        self.group_box_selected_warehouse.setTitle(_translate("MainWindow", "Selected warehouse information"))
        self.label_warehouse_information_id.setText(_translate("MainWindow", "Warehouse id"))
        self.label_warehouse_information_id_show.setText(_translate("MainWindow", "None"))
        self.label_warehouse_information_name.setText(_translate("MainWindow", "Warehouse name"))
        self.label_warehouse_information_name_show.setText(_translate("MainWindow", "None"))
        self.label_warehouse_information_street_show.setText(_translate("MainWindow", "None"))
        self.label_warehouse_information_city_show.setText(_translate("MainWindow", "None"))
        self.label_warehouse_information_city.setText(_translate("MainWindow", "Warehouse city"))
        self.label_warehouse_information_street.setText(_translate("MainWindow", "Warehouse street"))
        self.label_warehouse_information_country_show.setText(_translate("MainWindow", "None"))
        self.label_warehouse_information_country.setText(_translate("MainWindow", "Warehouse country"))
        self.push_button_select_warehouse.setText(_translate("MainWindow", "Select warehouse"))
        self.button_show_products.setText(_translate("MainWindow", "Show Products"))
        self.button_show_warehouses.setText(_translate("MainWindow", "Show warehouses"))
        self.button_find_warehouse_by_product.setText(_translate("MainWindow", "Find"))
        self.label_find_warehouse_by_prodcut_name.setText(_translate("MainWindow", "Find warehouse by product name"))
        self.groupBox.setTitle(_translate("MainWindow", "Delete warehouse or product"))
        self.label_delete_warehouse.setText(_translate("MainWindow", "Delete by warehousue id"))
        self.label_delete_products.setText(_translate("MainWindow", "Delete by product id"))
        self.button_delete_warehouse.setText(_translate("MainWindow", "Delete warehouse"))
        self.button_delete_product.setText(_translate("MainWindow", "Delete product"))
        self.label_warehouse_city.setText(_translate("MainWindow", "Warehouse city"))
        self.label_warehouse_street.setText(_translate("MainWindow", "Warehouse street"))
        self.label_warehouse_name.setText(_translate("MainWindow", "Warehouse name"))
        self.button_save_warehouse.setText(_translate("MainWindow", "Save"))
        self.label_warehouse_country.setText(_translate("MainWindow", "Warehouse country"))
        self.tab_warehouse.setTabText(self.tab_warehouse.indexOf(self.tab_add_warehouse), _translate("MainWindow", "Add warehouse"))
        self.label_warehouse_city_edit.setText(_translate("MainWindow", "Warehouse city"))
        self.label_warehouse_street_edit.setText(_translate("MainWindow", "Warehouse street"))
        self.label_warehouse_name_edit.setText(_translate("MainWindow", "Warehouse name"))
        self.button_edit_warehouse.setText(_translate("MainWindow", "Edit"))
        self.label_warehouse_country_edit.setText(_translate("MainWindow", "Warehouse country"))
        self.label_warehouse_id_edit.setText(_translate("MainWindow", "Warehouse id"))
        self.tab_warehouse.setTabText(self.tab_warehouse.indexOf(self.tab_edit_warehouse), _translate("MainWindow", "Edit warehouse"))
        self.label_product_warehouse_id.setText(_translate("MainWindow", "Warehouse id"))
        self.label_product_name.setText(_translate("MainWindow", "Name"))
        self.label_product_quantity.setText(_translate("MainWindow", "Quantity"))
        self.button_save_product.setText(_translate("MainWindow", "Save"))
        self.label_product_category.setText(_translate("MainWindow", "Categorty"))
        self.label_product_price.setText(_translate("MainWindow", "Price"))
        self.tab_products.setTabText(self.tab_products.indexOf(self.tab_add_product), _translate("MainWindow", "Add product"))
        self.label_product_name_edit.setText(_translate("MainWindow", "Name"))
        self.label_product_price_edit.setText(_translate("MainWindow", "Price"))
        self.label_product_warehouse_id_edit.setText(_translate("MainWindow", "Warehouse id"))
        self.label_product_quantity_edit.setText(_translate("MainWindow", "Quantity"))
        self.label_product_category_edit.setText(_translate("MainWindow", "Categorty"))
        self.button_edit_products.setText(_translate("MainWindow", "Edit"))
        self.label_product_id_edit.setText(_translate("MainWindow", "Product id"))
        self.tab_products.setTabText(self.tab_products.indexOf(self.tab_edit_product), _translate("MainWindow", "Edit product"))
        self.labela_add_picture_id.setText(_translate("MainWindow", "Add product picture by product id"))
        self.button_select_picture.setText(_translate("MainWindow", "Select picture"))
        self.button_save_picture.setText(_translate("MainWindow", "Save to database"))
        self.label_file_name.setText(_translate("MainWindow", "File name:"))
        self.label_show_picture_id.setText(_translate("MainWindow", "Enter product ID which picture you would like to see"))
        self.button_show_picture.setText(_translate("MainWindow", "Show picture"))
        self.tab_products.setTabText(self.tab_products.indexOf(self.tab_picture_product), _translate("MainWindow", "Add/Show product picture"))
        self.group_box_reports.setTitle(_translate("MainWindow", "Reports"))
        self.button_generate_reports.setText(_translate("MainWindow", "Generate reports"))
        self.button_show_reports.setText(_translate("MainWindow", "Show reports"))
        self.groupBox_total_cost.setTitle(_translate("MainWindow", "Total cost of all products"))
        self.label_refresh.setText(_translate("MainWindow", "Time of the data refresh:"))
        self.label_sum_product_price.setText(_translate("MainWindow", "Sum of product price in HRK:"))
        self.groupBox_exchange_rate.setTitle(_translate("MainWindow", "Total product price in other currencies"))
        self.label_eur.setText(_translate("MainWindow", "EUR:"))
        self.label_eur_show.setText(_translate("MainWindow", ""))
        self.label_usd.setText(_translate("MainWindow", "USD:"))
        self.label_usd_show.setText(_translate("MainWindow", ""))
        self.label_cad.setText(_translate("MainWindow", "CAD:"))
        self.label_cad_show.setText(_translate("MainWindow", ""))
        self.label_aud.setText(_translate("MainWindow", "AUD:"))
        self.label_aud_show.setText(_translate("MainWindow", ""))
        self.label_gbp_show.setText(_translate("MainWindow", ""))
        self.label_gbp.setText(_translate("MainWindow", "GBP:"))
        self.button_convert_currencies.setText(_translate("MainWindow", "Convert"))