# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'database_view_windowIgWQHo.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1300, 675)
        self.actionQuit = QAction(MainWindow)
        self.actionQuit.setObjectName(u"actionQuit")
        self.actionAdd_picture_to_product = QAction(MainWindow)
        self.actionAdd_picture_to_product.setObjectName(u"actionAdd_picture_to_product")
        self.actionShow_Report = QAction(MainWindow)
        self.actionShow_Report.setObjectName(u"actionShow_Report")
        self.actionShow_Report.setCheckable(False)
        self.actionGenerate_reports = QAction(MainWindow)
        self.actionGenerate_reports.setObjectName(u"actionGenerate_reports")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.table_proizvodi = QTableWidget(self.centralwidget)
        self.table_proizvodi.setObjectName(u"table_proizvodi")
        self.table_proizvodi.setGeometry(QRect(30, 410, 691, 201))
        self.group_box_information = QGroupBox(self.centralwidget)
        self.group_box_information.setObjectName(u"group_box_information")
        self.group_box_information.setGeometry(QRect(10, 10, 311, 71))
        self.label_active_language_show = QLabel(self.group_box_information)
        self.label_active_language_show.setObjectName(u"label_active_language_show")
        self.label_active_language_show.setGeometry(QRect(80, 40, 47, 21))
        self.label_active_user = QLabel(self.group_box_information)
        self.label_active_user.setObjectName(u"label_active_user")
        self.label_active_user.setGeometry(QRect(10, 20, 61, 21))
        self.label_active_user_show = QLabel(self.group_box_information)
        self.label_active_user_show.setObjectName(u"label_active_user_show")
        self.label_active_user_show.setGeometry(QRect(80, 20, 47, 21))
        self.label_active_language = QLabel(self.group_box_information)
        self.label_active_language.setObjectName(u"label_active_language")
        self.label_active_language.setGeometry(QRect(10, 40, 61, 21))
        self.label_date = QLabel(self.group_box_information)
        self.label_date.setObjectName(u"label_date")
        self.label_date.setGeometry(QRect(180, 20, 31, 21))
        self.label_time_show = QLabel(self.group_box_information)
        self.label_time_show.setObjectName(u"label_time_show")
        self.label_time_show.setGeometry(QRect(220, 40, 71, 21))
        self.label_date_show = QLabel(self.group_box_information)
        self.label_date_show.setObjectName(u"label_date_show")
        self.label_date_show.setGeometry(QRect(220, 20, 71, 21))
        self.label_time = QLabel(self.group_box_information)
        self.label_time.setObjectName(u"label_time")
        self.label_time.setGeometry(QRect(180, 40, 31, 21))
        self.group_box_selected_warehouse = QGroupBox(self.centralwidget)
        self.group_box_selected_warehouse.setObjectName(u"group_box_selected_warehouse")
        self.group_box_selected_warehouse.setGeometry(QRect(10, 100, 300, 243))
        self.label_warehouse_information_id = QLabel(self.group_box_selected_warehouse)
        self.label_warehouse_information_id.setObjectName(u"label_warehouse_information_id")
        self.label_warehouse_information_id.setGeometry(QRect(20, 40, 111, 16))
        self.label_warehouse_information_id_show = QLabel(self.group_box_selected_warehouse)
        self.label_warehouse_information_id_show.setObjectName(u"label_warehouse_information_id_show")
        self.label_warehouse_information_id_show.setGeometry(QRect(140, 40, 141, 16))
        self.label_warehouse_information_name = QLabel(self.group_box_selected_warehouse)
        self.label_warehouse_information_name.setObjectName(u"label_warehouse_information_name")
        self.label_warehouse_information_name.setGeometry(QRect(20, 60, 111, 16))
        self.label_warehouse_information_name_show = QLabel(self.group_box_selected_warehouse)
        self.label_warehouse_information_name_show.setObjectName(u"label_warehouse_information_name_show")
        self.label_warehouse_information_name_show.setGeometry(QRect(140, 60, 141, 16))
        self.label_warehouse_information_street_show = QLabel(self.group_box_selected_warehouse)
        self.label_warehouse_information_street_show.setObjectName(u"label_warehouse_information_street_show")
        self.label_warehouse_information_street_show.setGeometry(QRect(140, 80, 131, 16))
        self.label_warehouse_information_city_show = QLabel(self.group_box_selected_warehouse)
        self.label_warehouse_information_city_show.setObjectName(u"label_warehouse_information_city_show")
        self.label_warehouse_information_city_show.setGeometry(QRect(140, 100, 131, 16))
        self.label_warehouse_information_city = QLabel(self.group_box_selected_warehouse)
        self.label_warehouse_information_city.setObjectName(u"label_warehouse_information_city")
        self.label_warehouse_information_city.setGeometry(QRect(20, 100, 111, 16))
        self.label_warehouse_information_street = QLabel(self.group_box_selected_warehouse)
        self.label_warehouse_information_street.setObjectName(u"label_warehouse_information_street")
        self.label_warehouse_information_street.setGeometry(QRect(20, 80, 111, 16))
        self.label_warehouse_information_country_show = QLabel(self.group_box_selected_warehouse)
        self.label_warehouse_information_country_show.setObjectName(u"label_warehouse_information_country_show")
        self.label_warehouse_information_country_show.setGeometry(QRect(140, 120, 141, 16))
        self.label_warehouse_information_country = QLabel(self.group_box_selected_warehouse)
        self.label_warehouse_information_country.setObjectName(u"label_warehouse_information_country")
        self.label_warehouse_information_country.setGeometry(QRect(20, 120, 111, 16))
        self.push_button_select_warehouse = QPushButton(self.group_box_selected_warehouse)
        self.push_button_select_warehouse.setObjectName(u"push_button_select_warehouse")
        self.push_button_select_warehouse.setGeometry(QRect(20, 180, 151, 23))
        self.line_edit_select_warehouse = QLineEdit(self.group_box_selected_warehouse)
        self.line_edit_select_warehouse.setObjectName(u"line_edit_select_warehouse")
        self.line_edit_select_warehouse.setGeometry(QRect(20, 150, 151, 20))
        self.table_show_warehouse_products = QTableView(self.centralwidget)
        self.table_show_warehouse_products.setObjectName(u"table_show_warehouse_products")
        self.table_show_warehouse_products.setGeometry(QRect(750, 410, 531, 201))
        self.button_show_products = QPushButton(self.centralwidget)
        self.button_show_products.setObjectName(u"button_show_products")
        self.button_show_products.setGeometry(QRect(750, 370, 251, 23))
        self.button_show_warehouses = QPushButton(self.centralwidget)
        self.button_show_warehouses.setObjectName(u"button_show_warehouses")
        self.button_show_warehouses.setGeometry(QRect(1030, 370, 251, 23))
        self.button_find_warehouse_by_product = QPushButton(self.centralwidget)
        self.button_find_warehouse_by_product.setObjectName(u"button_find_warehouse_by_product")
        self.button_find_warehouse_by_product.setGeometry(QRect(40, 370, 91, 23))
        self.edit_find_warehouse_by_product = QLineEdit(self.centralwidget)
        self.edit_find_warehouse_by_product.setObjectName(u"edit_find_warehouse_by_product")
        self.edit_find_warehouse_by_product.setGeometry(QRect(140, 370, 181, 20))
        self.group_delete_warehouse_product = QGroupBox(self.centralwidget)
        self.group_delete_warehouse_product.setObjectName(u"group_delete_warehouse_product")
        self.group_delete_warehouse_product.setGeometry(QRect(970, 100, 300, 241))
        self.label_delete_warehouse = QLabel(self.group_delete_warehouse_product)
        self.label_delete_warehouse.setObjectName(u"label_delete_warehouse")
        self.label_delete_warehouse.setGeometry(QRect(20, 40, 261, 20))
        self.label_delete_products = QLabel(self.group_delete_warehouse_product)
        self.label_delete_products.setObjectName(u"label_delete_products")
        self.label_delete_products.setGeometry(QRect(20, 140, 261, 20))
        self.button_delete_warehouse = QPushButton(self.group_delete_warehouse_product)
        self.button_delete_warehouse.setObjectName(u"button_delete_warehouse")
        self.button_delete_warehouse.setGeometry(QRect(20, 100, 251, 23))
        self.edit_delete_warehouse = QLineEdit(self.group_delete_warehouse_product)
        self.edit_delete_warehouse.setObjectName(u"edit_delete_warehouse")
        self.edit_delete_warehouse.setGeometry(QRect(20, 70, 251, 20))
        self.edit_delete_products = QLineEdit(self.group_delete_warehouse_product)
        self.edit_delete_products.setObjectName(u"edit_delete_products")
        self.edit_delete_products.setGeometry(QRect(20, 170, 251, 20))
        self.button_delete_product = QPushButton(self.group_delete_warehouse_product)
        self.button_delete_product.setObjectName(u"button_delete_product")
        self.button_delete_product.setGeometry(QRect(20, 200, 251, 23))
        self.tab_warehouse = QTabWidget(self.centralwidget)
        self.tab_warehouse.setObjectName(u"tab_warehouse")
        self.tab_warehouse.setGeometry(QRect(330, 90, 300, 251))
        self.tab_add_warehouse = QWidget()
        self.tab_add_warehouse.setObjectName(u"tab_add_warehouse")
        self.line_edit_warehoue_city = QLineEdit(self.tab_add_warehouse)
        self.line_edit_warehoue_city.setObjectName(u"line_edit_warehoue_city")
        self.line_edit_warehoue_city.setGeometry(QRect(130, 80, 151, 20))
        self.label_warehouse_city = QLabel(self.tab_add_warehouse)
        self.label_warehouse_city.setObjectName(u"label_warehouse_city")
        self.label_warehouse_city.setGeometry(QRect(20, 80, 101, 20))
        self.label_warehouse_street = QLabel(self.tab_add_warehouse)
        self.label_warehouse_street.setObjectName(u"label_warehouse_street")
        self.label_warehouse_street.setGeometry(QRect(20, 50, 101, 21))
        self.label_warehouse_name = QLabel(self.tab_add_warehouse)
        self.label_warehouse_name.setObjectName(u"label_warehouse_name")
        self.label_warehouse_name.setGeometry(QRect(20, 20, 101, 20))
        self.line_edit_warehoue_street = QLineEdit(self.tab_add_warehouse)
        self.line_edit_warehoue_street.setObjectName(u"line_edit_warehoue_street")
        self.line_edit_warehoue_street.setGeometry(QRect(130, 50, 151, 20))
        self.button_save_warehouse = QPushButton(self.tab_add_warehouse)
        self.button_save_warehouse.setObjectName(u"button_save_warehouse")
        self.button_save_warehouse.setGeometry(QRect(20, 150, 261, 23))
        self.line_edit_warehoue_name = QLineEdit(self.tab_add_warehouse)
        self.line_edit_warehoue_name.setObjectName(u"line_edit_warehoue_name")
        self.line_edit_warehoue_name.setGeometry(QRect(130, 20, 151, 20))
        self.label_warehouse_country = QLabel(self.tab_add_warehouse)
        self.label_warehouse_country.setObjectName(u"label_warehouse_country")
        self.label_warehouse_country.setGeometry(QRect(20, 110, 101, 20))
        self.line_edit_warehoue_country = QLineEdit(self.tab_add_warehouse)
        self.line_edit_warehoue_country.setObjectName(u"line_edit_warehoue_country")
        self.line_edit_warehoue_country.setGeometry(QRect(130, 110, 151, 20))
        self.tab_warehouse.addTab(self.tab_add_warehouse, "")
        self.tab_edit_warehouse = QWidget()
        self.tab_edit_warehouse.setObjectName(u"tab_edit_warehouse")
        self.label_warehouse_city_edit = QLabel(self.tab_edit_warehouse)
        self.label_warehouse_city_edit.setObjectName(u"label_warehouse_city_edit")
        self.label_warehouse_city_edit.setGeometry(QRect(20, 100, 101, 20))
        self.label_warehouse_street_edit = QLabel(self.tab_edit_warehouse)
        self.label_warehouse_street_edit.setObjectName(u"label_warehouse_street_edit")
        self.label_warehouse_street_edit.setGeometry(QRect(20, 70, 101, 21))
        self.label_warehouse_name_edit = QLabel(self.tab_edit_warehouse)
        self.label_warehouse_name_edit.setObjectName(u"label_warehouse_name_edit")
        self.label_warehouse_name_edit.setGeometry(QRect(20, 40, 101, 20))
        self.button_edit_warehouse = QPushButton(self.tab_edit_warehouse)
        self.button_edit_warehouse.setObjectName(u"button_edit_warehouse")
        self.button_edit_warehouse.setGeometry(QRect(20, 170, 261, 23))
        self.line_edit_warehoue_city_edit = QLineEdit(self.tab_edit_warehouse)
        self.line_edit_warehoue_city_edit.setObjectName(u"line_edit_warehoue_city_edit")
        self.line_edit_warehoue_city_edit.setGeometry(QRect(130, 100, 151, 20))
        self.line_edit_warehoue_street_edit = QLineEdit(self.tab_edit_warehouse)
        self.line_edit_warehoue_street_edit.setObjectName(u"line_edit_warehoue_street_edit")
        self.line_edit_warehoue_street_edit.setGeometry(QRect(130, 70, 151, 20))
        self.line_edit_warehoue_name_edit = QLineEdit(self.tab_edit_warehouse)
        self.line_edit_warehoue_name_edit.setObjectName(u"line_edit_warehoue_name_edit")
        self.line_edit_warehoue_name_edit.setGeometry(QRect(130, 40, 151, 20))
        self.label_warehouse_country_edit = QLabel(self.tab_edit_warehouse)
        self.label_warehouse_country_edit.setObjectName(u"label_warehouse_country_edit")
        self.label_warehouse_country_edit.setGeometry(QRect(20, 130, 101, 20))
        self.line_edit_warehoue_country_edit = QLineEdit(self.tab_edit_warehouse)
        self.line_edit_warehoue_country_edit.setObjectName(u"line_edit_warehoue_country_edit")
        self.line_edit_warehoue_country_edit.setGeometry(QRect(130, 130, 151, 20))
        self.label_warehouse_id_edit = QLabel(self.tab_edit_warehouse)
        self.label_warehouse_id_edit.setObjectName(u"label_warehouse_id_edit")
        self.label_warehouse_id_edit.setGeometry(QRect(20, 10, 101, 20))
        self.line_edit_warehoue_name_id_edit = QLineEdit(self.tab_edit_warehouse)
        self.line_edit_warehoue_name_id_edit.setObjectName(u"line_edit_warehoue_name_id_edit")
        self.line_edit_warehoue_name_id_edit.setGeometry(QRect(130, 10, 151, 20))
        self.tab_warehouse.addTab(self.tab_edit_warehouse, "")
        self.tab_products = QTabWidget(self.centralwidget)
        self.tab_products.setObjectName(u"tab_products")
        self.tab_products.setGeometry(QRect(650, 90, 300, 251))
        self.tab_add_product = QWidget()
        self.tab_add_product.setObjectName(u"tab_add_product")
        self.line_edit_products_warehouse_id = QLineEdit(self.tab_add_product)
        self.line_edit_products_warehouse_id.setObjectName(u"line_edit_products_warehouse_id")
        self.line_edit_products_warehouse_id.setGeometry(QRect(100, 20, 181, 20))
        self.label_product_warehouse_id = QLabel(self.tab_add_product)
        self.label_product_warehouse_id.setObjectName(u"label_product_warehouse_id")
        self.label_product_warehouse_id.setGeometry(QRect(20, 20, 71, 20))
        self.line_edit_products_quantity = QLineEdit(self.tab_add_product)
        self.line_edit_products_quantity.setObjectName(u"line_edit_products_quantity")
        self.line_edit_products_quantity.setGeometry(QRect(100, 110, 181, 20))
        self.line_edit_products_category = QLineEdit(self.tab_add_product)
        self.line_edit_products_category.setObjectName(u"line_edit_products_category")
        self.line_edit_products_category.setGeometry(QRect(100, 140, 181, 20))
        self.label_product_name = QLabel(self.tab_add_product)
        self.label_product_name.setObjectName(u"label_product_name")
        self.label_product_name.setGeometry(QRect(20, 50, 71, 21))
        self.label_product_quantity = QLabel(self.tab_add_product)
        self.label_product_quantity.setObjectName(u"label_product_quantity")
        self.label_product_quantity.setGeometry(QRect(20, 110, 71, 21))
        self.label_product_quantity.setScaledContents(False)
        self.label_product_quantity.setWordWrap(False)
        self.line_edit_products_name = QLineEdit(self.tab_add_product)
        self.line_edit_products_name.setObjectName(u"line_edit_products_name")
        self.line_edit_products_name.setGeometry(QRect(100, 50, 181, 20))
        self.button_save_product = QPushButton(self.tab_add_product)
        self.button_save_product.setObjectName(u"button_save_product")
        self.button_save_product.setGeometry(QRect(20, 170, 261, 23))
        self.line_edit_products_price = QLineEdit(self.tab_add_product)
        self.line_edit_products_price.setObjectName(u"line_edit_products_price")
        self.line_edit_products_price.setGeometry(QRect(100, 80, 181, 20))
        self.label_product_category = QLabel(self.tab_add_product)
        self.label_product_category.setObjectName(u"label_product_category")
        self.label_product_category.setGeometry(QRect(20, 140, 71, 21))
        self.label_product_category.setScaledContents(False)
        self.label_product_category.setWordWrap(False)
        self.label_product_price = QLabel(self.tab_add_product)
        self.label_product_price.setObjectName(u"label_product_price")
        self.label_product_price.setGeometry(QRect(20, 80, 71, 21))
        self.tab_products.addTab(self.tab_add_product, "")
        self.tab_edit_product = QWidget()
        self.tab_edit_product.setObjectName(u"tab_edit_product")
        self.label_product_name_edit = QLabel(self.tab_edit_product)
        self.label_product_name_edit.setObjectName(u"label_product_name_edit")
        self.label_product_name_edit.setGeometry(QRect(20, 70, 71, 21))
        self.label_product_price_edit = QLabel(self.tab_edit_product)
        self.label_product_price_edit.setObjectName(u"label_product_price_edit")
        self.label_product_price_edit.setGeometry(QRect(20, 100, 71, 21))
        self.label_product_warehouse_id_edit = QLabel(self.tab_edit_product)
        self.label_product_warehouse_id_edit.setObjectName(u"label_product_warehouse_id_edit")
        self.label_product_warehouse_id_edit.setGeometry(QRect(20, 40, 71, 20))
        self.label_product_quantity_edit = QLabel(self.tab_edit_product)
        self.label_product_quantity_edit.setObjectName(u"label_product_quantity_edit")
        self.label_product_quantity_edit.setGeometry(QRect(20, 130, 71, 21))
        self.label_product_quantity_edit.setScaledContents(False)
        self.label_product_quantity_edit.setWordWrap(False)
        self.line_edit_products_price_edit = QLineEdit(self.tab_edit_product)
        self.line_edit_products_price_edit.setObjectName(u"line_edit_products_price_edit")
        self.line_edit_products_price_edit.setGeometry(QRect(100, 100, 181, 20))
        self.label_product_category_edit = QLabel(self.tab_edit_product)
        self.label_product_category_edit.setObjectName(u"label_product_category_edit")
        self.label_product_category_edit.setGeometry(QRect(20, 160, 71, 21))
        self.label_product_category_edit.setScaledContents(False)
        self.label_product_category_edit.setWordWrap(False)
        self.line_edit_products_category_edit = QLineEdit(self.tab_edit_product)
        self.line_edit_products_category_edit.setObjectName(u"line_edit_products_category_edit")
        self.line_edit_products_category_edit.setGeometry(QRect(100, 160, 181, 20))
        self.line_edit_products_quantity_edit = QLineEdit(self.tab_edit_product)
        self.line_edit_products_quantity_edit.setObjectName(u"line_edit_products_quantity_edit")
        self.line_edit_products_quantity_edit.setGeometry(QRect(100, 130, 181, 20))
        self.button_edit_products = QPushButton(self.tab_edit_product)
        self.button_edit_products.setObjectName(u"button_edit_products")
        self.button_edit_products.setGeometry(QRect(20, 190, 261, 23))
        self.line_edit_products_name_edit = QLineEdit(self.tab_edit_product)
        self.line_edit_products_name_edit.setObjectName(u"line_edit_products_name_edit")
        self.line_edit_products_name_edit.setGeometry(QRect(100, 70, 181, 20))
        self.line_edit_products_warehouse_id_edit = QLineEdit(self.tab_edit_product)
        self.line_edit_products_warehouse_id_edit.setObjectName(u"line_edit_products_warehouse_id_edit")
        self.line_edit_products_warehouse_id_edit.setGeometry(QRect(100, 40, 181, 20))
        self.label_product_id_edit = QLabel(self.tab_edit_product)
        self.label_product_id_edit.setObjectName(u"label_product_id_edit")
        self.label_product_id_edit.setGeometry(QRect(20, 10, 71, 20))
        self.line_edit_product_id = QLineEdit(self.tab_edit_product)
        self.line_edit_product_id.setObjectName(u"line_edit_product_id")
        self.line_edit_product_id.setGeometry(QRect(100, 10, 181, 20))
        self.tab_products.addTab(self.tab_edit_product, "")
        self.tab_picture_product = QWidget()
        self.tab_picture_product.setObjectName(u"tab_picture_product")
        self.labela_add_picture_id = QLabel(self.tab_picture_product)
        self.labela_add_picture_id.setObjectName(u"labela_add_picture_id")
        self.labela_add_picture_id.setGeometry(QRect(20, 20, 251, 21))
        self.edit_add_picture_id = QLineEdit(self.tab_picture_product)
        self.edit_add_picture_id.setObjectName(u"edit_add_picture_id")
        self.edit_add_picture_id.setGeometry(QRect(20, 50, 251, 20))
        self.button_select_picture = QPushButton(self.tab_picture_product)
        self.button_select_picture.setObjectName(u"button_select_picture")
        self.button_select_picture.setGeometry(QRect(20, 80, 121, 23))
        self.button_save_picture = QPushButton(self.tab_picture_product)
        self.button_save_picture.setObjectName(u"button_save_picture")
        self.button_save_picture.setGeometry(QRect(150, 80, 121, 23))
        self.label_file_name = QLabel(self.tab_picture_product)
        self.label_file_name.setObjectName(u"label_file_name")
        self.label_file_name.setGeometry(QRect(20, 110, 111, 20))
        self.label_file_name_show = QLabel(self.tab_picture_product)
        self.label_file_name_show.setObjectName(u"label_file_name_show")
        self.label_file_name_show.setGeometry(QRect(146, 110, 121, 20))
        self.label_show_picture_id = QLabel(self.tab_picture_product)
        self.label_show_picture_id.setObjectName(u"label_show_picture_id")
        self.label_show_picture_id.setGeometry(QRect(20, 140, 251, 16))
        self.edit_show_picture_id = QLineEdit(self.tab_picture_product)
        self.edit_show_picture_id.setObjectName(u"edit_show_picture_id")
        self.edit_show_picture_id.setGeometry(QRect(20, 170, 113, 20))
        self.button_show_picture = QPushButton(self.tab_picture_product)
        self.button_show_picture.setObjectName(u"button_show_picture")
        self.button_show_picture.setGeometry(QRect(150, 170, 121, 23))
        self.tab_products.addTab(self.tab_picture_product, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setEnabled(True)
        self.menubar.setGeometry(QRect(0, 0, 1300, 21))
        self.menubar.setDefaultUp(False)
        self.menuOther_actions = QMenu(self.menubar)
        self.menuOther_actions.setObjectName(u"menuOther_actions")
        self.menuReports = QMenu(self.menuOther_actions)
        self.menuReports.setObjectName(u"menuReports")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuOther_actions.menuAction())
        self.menuOther_actions.addAction(self.menuReports.menuAction())
        self.menuReports.addAction(self.actionShow_Report)
        self.menuReports.addAction(self.actionGenerate_reports)

        self.retranslateUi(MainWindow)

        self.tab_warehouse.setCurrentIndex(0)
        self.tab_products.setCurrentIndex(2)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionQuit.setText(QCoreApplication.translate("MainWindow", u"Quit", None))
        self.actionAdd_picture_to_product.setText(QCoreApplication.translate("MainWindow", u"Add picture to product", None))
        self.actionShow_Report.setText(QCoreApplication.translate("MainWindow", u"Show Report", None))
        self.actionGenerate_reports.setText(QCoreApplication.translate("MainWindow", u"Generate reports", None))
        self.group_box_information.setTitle(QCoreApplication.translate("MainWindow", u"Information", None))
        self.label_active_language_show.setText(QCoreApplication.translate("MainWindow", u"None", None))
        self.label_active_user.setText(QCoreApplication.translate("MainWindow", u"Active user:", None))
        self.label_active_user_show.setText(QCoreApplication.translate("MainWindow", u"None", None))
        self.label_active_language.setText(QCoreApplication.translate("MainWindow", u"Language:", None))
        self.label_date.setText(QCoreApplication.translate("MainWindow", u"Date:", None))
        self.label_time_show.setText(QCoreApplication.translate("MainWindow", u"None", None))
        self.label_date_show.setText(QCoreApplication.translate("MainWindow", u"None", None))
        self.label_time.setText(QCoreApplication.translate("MainWindow", u"Time:", None))
        self.group_box_selected_warehouse.setTitle(QCoreApplication.translate("MainWindow", u"Selected warehouse information", None))
        self.label_warehouse_information_id.setText(QCoreApplication.translate("MainWindow", u"Warehouse id", None))
        self.label_warehouse_information_id_show.setText(QCoreApplication.translate("MainWindow", u"None", None))
        self.label_warehouse_information_name.setText(QCoreApplication.translate("MainWindow", u"Warehouse name", None))
        self.label_warehouse_information_name_show.setText(QCoreApplication.translate("MainWindow", u"None", None))
        self.label_warehouse_information_street_show.setText(QCoreApplication.translate("MainWindow", u"None", None))
        self.label_warehouse_information_city_show.setText(QCoreApplication.translate("MainWindow", u"None", None))
        self.label_warehouse_information_city.setText(QCoreApplication.translate("MainWindow", u"Warehouse city", None))
        self.label_warehouse_information_street.setText(QCoreApplication.translate("MainWindow", u"Warehouse street", None))
        self.label_warehouse_information_country_show.setText(QCoreApplication.translate("MainWindow", u"None", None))
        self.label_warehouse_information_country.setText(QCoreApplication.translate("MainWindow", u"Warehouse country", None))
        self.push_button_select_warehouse.setText(QCoreApplication.translate("MainWindow", u"Select warehouse", None))
        self.button_show_products.setText(QCoreApplication.translate("MainWindow", u"Show Products", None))
        self.button_show_warehouses.setText(QCoreApplication.translate("MainWindow", u"Show warehouses", None))
        self.button_find_warehouse_by_product.setText(QCoreApplication.translate("MainWindow", u"Find", None))
        self.group_delete_warehouse_product.setTitle(QCoreApplication.translate("MainWindow", u"Delete warehouse or product", None))
        self.label_delete_warehouse.setText(QCoreApplication.translate("MainWindow", u"Delete by warehousue id", None))
        self.label_delete_products.setText(QCoreApplication.translate("MainWindow", u"Delete by product id", None))
        self.button_delete_warehouse.setText(QCoreApplication.translate("MainWindow", u"Delete warehouse", None))
        self.button_delete_product.setText(QCoreApplication.translate("MainWindow", u"Delete product", None))
        self.label_warehouse_city.setText(QCoreApplication.translate("MainWindow", u"Warehouse city", None))
        self.label_warehouse_street.setText(QCoreApplication.translate("MainWindow", u"Warehouse street", None))
        self.label_warehouse_name.setText(QCoreApplication.translate("MainWindow", u"Warehouse name", None))
        self.button_save_warehouse.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.label_warehouse_country.setText(QCoreApplication.translate("MainWindow", u"Warehouse country", None))
        self.tab_warehouse.setTabText(self.tab_warehouse.indexOf(self.tab_add_warehouse), QCoreApplication.translate("MainWindow", u"Add warehouse", None))
        self.label_warehouse_city_edit.setText(QCoreApplication.translate("MainWindow", u"Warehouse city", None))
        self.label_warehouse_street_edit.setText(QCoreApplication.translate("MainWindow", u"Warehouse street", None))
        self.label_warehouse_name_edit.setText(QCoreApplication.translate("MainWindow", u"Warehouse name", None))
        self.button_edit_warehouse.setText(QCoreApplication.translate("MainWindow", u"Edit", None))
        self.label_warehouse_country_edit.setText(QCoreApplication.translate("MainWindow", u"Warehouse country", None))
        self.label_warehouse_id_edit.setText(QCoreApplication.translate("MainWindow", u"Warehouse id", None))
        self.tab_warehouse.setTabText(self.tab_warehouse.indexOf(self.tab_edit_warehouse), QCoreApplication.translate("MainWindow", u"Edit warehouse", None))
        self.label_product_warehouse_id.setText(QCoreApplication.translate("MainWindow", u"Warehouse id", None))
        self.label_product_name.setText(QCoreApplication.translate("MainWindow", u"Name", None))
        self.label_product_quantity.setText(QCoreApplication.translate("MainWindow", u"Quantity", None))
        self.button_save_product.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.label_product_category.setText(QCoreApplication.translate("MainWindow", u"Categorty", None))
        self.label_product_price.setText(QCoreApplication.translate("MainWindow", u"Price", None))
        self.tab_products.setTabText(self.tab_products.indexOf(self.tab_add_product), QCoreApplication.translate("MainWindow", u"Add product", None))
        self.label_product_name_edit.setText(QCoreApplication.translate("MainWindow", u"Name", None))
        self.label_product_price_edit.setText(QCoreApplication.translate("MainWindow", u"Price", None))
        self.label_product_warehouse_id_edit.setText(QCoreApplication.translate("MainWindow", u"Warehouse id", None))
        self.label_product_quantity_edit.setText(QCoreApplication.translate("MainWindow", u"Quantity", None))
        self.label_product_category_edit.setText(QCoreApplication.translate("MainWindow", u"Categorty", None))
        self.button_edit_products.setText(QCoreApplication.translate("MainWindow", u"Edit", None))
        self.label_product_id_edit.setText(QCoreApplication.translate("MainWindow", u"Product id", None))
        self.tab_products.setTabText(self.tab_products.indexOf(self.tab_edit_product), QCoreApplication.translate("MainWindow", u"Edit product", None))
        self.labela_add_picture_id.setText(QCoreApplication.translate("MainWindow", u"Add product picture by product id", None))
        self.button_select_picture.setText(QCoreApplication.translate("MainWindow", u"Select picture", None))
        self.button_save_picture.setText(QCoreApplication.translate("MainWindow", u"Save to database", None))
        self.label_file_name.setText(QCoreApplication.translate("MainWindow", u"File name:", None))
        self.label_file_name_show.setText(QCoreApplication.translate("MainWindow", u"None", None))
        self.label_show_picture_id.setText(QCoreApplication.translate("MainWindow", u"Enter product ID which picture you would like to see", None))
        self.button_show_picture.setText(QCoreApplication.translate("MainWindow", u"Show picture", None))
        self.tab_products.setTabText(self.tab_products.indexOf(self.tab_picture_product), QCoreApplication.translate("MainWindow", u"Add/Show product picture", None))
        self.menuOther_actions.setTitle(QCoreApplication.translate("MainWindow", u"Other actions", None))
        self.menuReports.setTitle(QCoreApplication.translate("MainWindow", u"Reports", None))
    # retranslateUi

