# Form implementation generated from reading ui file 'show_image_form.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(361, 481)
        
        self.grup_box_frame_show_Image = QtWidgets.QGroupBox(parent=Form)
        self.grup_box_frame_show_Image.setGeometry(QtCore.QRect(20, 10, 321, 421))
        self.grup_box_frame_show_Image.setObjectName("grup_box_frame_show_Image")
        
        self.frame_show_image = QtWidgets.QFrame(parent=self.grup_box_frame_show_Image)
        self.frame_show_image.setGeometry(QtCore.QRect(10, 20, 301, 391))
        self.frame_show_image.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_show_image.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_show_image.setObjectName("frame_show_image")
        
        self.button_close_window = QtWidgets.QPushButton(parent=Form)
        self.button_close_window.setGeometry(QtCore.QRect(20, 440, 321, 23))
        self.button_close_window.setObjectName("button_close_window")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.grup_box_frame_show_Image.setTitle(_translate("Form", "GroupBox"))
        self.button_close_window.setText(_translate("Form", "Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
