# Form implementation generated from reading ui file '.\soap_client.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_soap_client(object):
    def setupUi(self, soap_client):
        soap_client.setObjectName("soap_client")
        soap_client.resize(707, 377)
        self.listView_country_codes = QtWidgets.QListView(parent=soap_client)
        self.listView_country_codes.setGeometry(QtCore.QRect(20, 30, 151, 192))
        self.listView_country_codes.setObjectName("listView_country_codes")
        self.label_country_codes = QtWidgets.QLabel(parent=soap_client)
        self.label_country_codes.setGeometry(QtCore.QRect(20, 10, 151, 16))
        self.label_country_codes.setObjectName("label_country_codes")
        self.label_enter_country_code = QtWidgets.QLabel(parent=soap_client)
        self.label_enter_country_code.setGeometry(QtCore.QRect(20, 236, 151, 20))
        self.label_enter_country_code.setObjectName("label_enter_country_code")
        self.lineEdit_enter_country_code = QtWidgets.QLineEdit(parent=soap_client)
        self.lineEdit_enter_country_code.setGeometry(QtCore.QRect(20, 260, 151, 20))
        self.lineEdit_enter_country_code.setObjectName("lineEdit_enter_country_code")
        self.pushButton_send_request = QtWidgets.QPushButton(parent=soap_client)
        self.pushButton_send_request.setGeometry(QtCore.QRect(20, 290, 151, 23))
        self.pushButton_send_request.setObjectName("pushButton_send_request")
        self.textBrowser_soap_message = QtWidgets.QTextBrowser(parent=soap_client)
        self.textBrowser_soap_message.setGeometry(QtCore.QRect(190, 30, 491, 192))
        self.textBrowser_soap_message.setObjectName("textBrowser_soap_message")
        self.label_request_code = QtWidgets.QLabel(parent=soap_client)
        self.label_request_code.setGeometry(QtCore.QRect(200, 230, 81, 16))
        self.label_request_code.setObjectName("label_request_code")
        self.label_show_request_code = QtWidgets.QLabel(parent=soap_client)
        self.label_show_request_code.setGeometry(QtCore.QRect(290, 230, 61, 16))
        self.label_show_request_code.setObjectName("label_show_request_code")
        self.label = QtWidgets.QLabel(parent=soap_client)
        self.label.setGeometry(QtCore.QRect(190, 10, 491, 16))
        self.label.setObjectName("label")

        self.retranslateUi(soap_client)
        QtCore.QMetaObject.connectSlotsByName(soap_client)

    def retranslateUi(self, soap_client):
        _translate = QtCore.QCoreApplication.translate
        soap_client.setWindowTitle(_translate("soap_client", "SOAP client"))
        self.label_country_codes.setText(_translate("soap_client", "Country codes:"))
        self.label_enter_country_code.setText(_translate("soap_client", "Enter country code:"))
        self.pushButton_send_request.setText(_translate("soap_client", "Send request"))
        self.label_request_code.setText(_translate("soap_client", "Request code:"))
        self.label_show_request_code.setText(_translate("soap_client", "None"))
        self.label.setText(_translate("soap_client", "SOAP message:"))
