# Form implementation generated from reading ui file '.\create_user.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(320, 321)
        self.group_box_create_user = QtWidgets.QGroupBox(parent=Form)
        self.group_box_create_user.setGeometry(QtCore.QRect(20, 20, 281, 271))
        self.group_box_create_user.setObjectName("group_box_create_user")
        self.button_create = QtWidgets.QPushButton(parent=self.group_box_create_user)
        self.button_create.setGeometry(QtCore.QRect(20, 130, 111, 24))
        self.button_create.setObjectName("button_create")
        self.button_exit = QtWidgets.QPushButton(parent=self.group_box_create_user)
        self.button_exit.setGeometry(QtCore.QRect(144, 130, 111, 24))
        self.button_exit.setObjectName("button_exit")
        self.line_edit_username = QtWidgets.QLineEdit(parent=self.group_box_create_user)
        self.line_edit_username.setGeometry(QtCore.QRect(100, 40, 151, 22))
        self.line_edit_username.setObjectName("line_edit_username")
        self.line_edit_password = QtWidgets.QLineEdit(parent=self.group_box_create_user)
        self.line_edit_password.setGeometry(QtCore.QRect(100, 80, 151, 22))
        self.line_edit_password.setObjectName("line_edit_password")
        self.label_username = QtWidgets.QLabel(parent=self.group_box_create_user)
        self.label_username.setGeometry(QtCore.QRect(20, 40, 81, 21))
        self.label_username.setObjectName("label_username")
        self.label_password = QtWidgets.QLabel(parent=self.group_box_create_user)
        self.label_password.setGeometry(QtCore.QRect(20, 80, 81, 21))
        self.label_password.setObjectName("label_password")
        self.label_information = QtWidgets.QLabel(parent=self.group_box_create_user)
        self.label_information.setGeometry(QtCore.QRect(20, 180, 241, 71))
        self.label_information.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_information.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_information.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.label_information.setWordWrap(True)
        self.label_information.setObjectName("label_information")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.group_box_create_user.setTitle(_translate("Form", "Create new user"))
        self.button_create.setText(_translate("Form", "Create"))
        self.button_exit.setText(_translate("Form", "Exit"))
        self.label_username.setText(_translate("Form", "Username"))
        self.label_password.setText(_translate("Form", "Password"))
        self.label_information.setText(_translate("Form", "none"))
