# Form implementation generated from reading ui file '.\login_form.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(235, 258)
        self.login_button = QtWidgets.QPushButton(parent=Form)
        self.login_button.setGeometry(QtCore.QRect(20, 110, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(8)
        self.login_button.setFont(font)
        self.login_button.setObjectName("login_button")
        self.exit_button = QtWidgets.QPushButton(parent=Form)
        self.exit_button.setGeometry(QtCore.QRect(120, 110, 91, 23))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(8)
        self.exit_button.setFont(font)
        self.exit_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.exit_button.setObjectName("exit_button")
        self.label_username = QtWidgets.QLabel(parent=Form)
        self.label_username.setGeometry(QtCore.QRect(20, 30, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(8)
        self.label_username.setFont(font)
        self.label_username.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.label_username.setObjectName("label_username")
        self.label_password = QtWidgets.QLabel(parent=Form)
        self.label_password.setGeometry(QtCore.QRect(20, 70, 71, 20))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(8)
        self.label_password.setFont(font)
        self.label_password.setObjectName("label_password")
        self.edit_username = QtWidgets.QLineEdit(parent=Form)
        self.edit_username.setGeometry(QtCore.QRect(100, 30, 113, 20))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(8)
        self.edit_username.setFont(font)
        self.edit_username.setObjectName("edit_username")
        self.edit_password = QtWidgets.QLineEdit(parent=Form)
        self.edit_password.setGeometry(QtCore.QRect(100, 70, 113, 20))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(8)
        self.edit_password.setFont(font)
        self.edit_password.setObjectName("edit_password")
        self.label_information = QtWidgets.QLabel(parent=Form)
        self.label_information.setGeometry(QtCore.QRect(20, 150, 181, 16))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(8)
        self.label_information.setFont(font)
        self.label_information.setObjectName("label_information")
        self.push_button_new_user = QtWidgets.QPushButton(parent=Form)
        self.push_button_new_user.setGeometry(QtCore.QRect(20, 190, 191, 24))
        self.push_button_new_user.setObjectName("push_button_new_user")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.login_button.setText(_translate("Form", "Login"))
        self.exit_button.setText(_translate("Form", "Exit"))
        self.label_username.setText(_translate("Form", "Username:"))
        self.label_password.setText(_translate("Form", "Password:"))
        self.label_information.setText(_translate("Form", "TextLabel"))
        self.push_button_new_user.setText(_translate("Form", "Create new user"))
