# Form implementation generated from reading ui file 'report.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(715, 490)
        self.label_product = QtWidgets.QLabel(parent=Form)
        self.label_product.setGeometry(QtCore.QRect(20, 10, 671, 31))
        self.label_product.setObjectName("label_product")
        self.textBrowser_product = QtWidgets.QTextBrowser(parent=Form)
        self.textBrowser_product.setGeometry(QtCore.QRect(20, 40, 671, 192))
        self.textBrowser_product.setObjectName("textBrowser_product")
        self.textBrowser_warehouse_product = QtWidgets.QTextBrowser(parent=Form)
        self.textBrowser_warehouse_product.setGeometry(QtCore.QRect(20, 280, 671, 192))
        self.textBrowser_warehouse_product.setObjectName("textBrowser_warehouse_product")
        self.label_warehouse_product = QtWidgets.QLabel(parent=Form)
        self.label_warehouse_product.setGeometry(QtCore.QRect(20, 240, 661, 31))
        self.label_warehouse_product.setObjectName("label_warehouse_product")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_product.setText(_translate("Form", "Table Product report"))
        self.label_warehouse_product.setText(_translate("Form", "Table Warehouse-Product Report"))
